### ISSUE TITLE
Fehlermeldung

### ISSUE THREAD

**Issue by TinsayeAbye** [serlo-org/athene2#118]
An sich ist es doch einfach nur eine falsche URL oder ? sollte doch kein Schwerwiegender Fehler Meldung kommen
https://de.serlo.org/taxonomy/term/9

**Comment by arekkas** [comment]
Ich nehme an, dass du auf die Seite gekommen bist, indem du IDs ausprobiert hast. Da dies ein Edge-Case ist, schließe ich die Issue (bist der erste der ihn gefunden hat).
