### ISSUE TITLE
Forum / Schwerwiegende fehler

### ISSUE THREAD

**Issue by TinsayeAbye** [serlo-org/athene2#119]
Wenn man nen neuen Forum mit dem selben namen eines bereits existierenden (Obwohl es im Trash ist) Namen eines forum category erstellen will kommt "schwerwiegede Fehler "  statt ein hinweis

**Comment by SimonKoehl** [comment]
Wir haben die Foren abgeschafft

**Comment by SimonKoehl** [comment]
Es gibt jetzt einfach einen linearen stream von Diskussionen. Und später im Idealfall für jeden Lerninhalt Leute, die sich verantwortlich fühlen. Das ganze Dinge mit der aktiven Zuweisung zu einem Forum war zu kompliziert gedacht.

**Comment by TinsayeAbye** [comment]
Achso okay
Das heißt beim seiten erstellen lasse ich Forum ID Leer

**Comment by SimonKoehl** [comment]
hm, gute Frage..
@arekkas wie können wir ohne Forum bestimmen, ob eine page Kommentare hat?
@TinsayeAbye gib für's erste einfach irgendeine bestehende Forum ID von Mathematik ein

**Comment by arekkas** [comment]
> hm, gute Frage..
@arekkas wie können wir ohne Forum bestimmen, ob eine page Kommentare hat?

ja

**Comment by arekkas** [comment]
Um hier ein bisschen back to topic zu kommen:

> Wenn man nen neuen Forum mit dem selben namen eines bereits existierenden (Obwohl es im Trash ist) Namen eines forum category erstellen will kommt "schwerwiegede Fehler " statt ein hinweis

Der Fehler ist bekannt, allerdings etwas schwerer zu beheben und sehr selten, daher auf der "Ignorier-Liste"

**Comment by SimonKoehl** [comment]
^^ thx
Was ich meine ist: Wenn man eine Seite neu anlegt, gibt man eine Forum ID an, wenn man Kommentare ermöglichen möchte. Ohne Forum ID - keine Kommentare. Nur haben wir das Forum ja abgeschafft..

**Comment by SimonKoehl** [comment]
oder benutzen wir dafür einfach weiterhin die Taxonomy vom Typ Forum im Hintergrund?

**Comment by arekkas** [comment]
Das kann man in zukunft über eine Checkbox machen ("Kommentare anzeigen?") - falls gewünscht bitte separat in Trello eintragen.

In Zukunft, falls möglich, Diskussionen auf Englisch halten, damit internationales Publikum auch erreicht wird.

**Comment by SimonKoehl** [comment]
ok, thx

good point
