### ISSUE TITLE
Kleiner Darstellungsfehler im Papierkorb

### ISSUE THREAD

**Issue by TinsayeAbye** [serlo-org/athene2#120]
![papierkorb](https://cloud.githubusercontent.com/assets/5862858/8267290/d42b4008-175a-11e5-8e11-92f44a0bce7b.JPG)

**Comment by inyono** [comment]
Seems like quotation marks are not encoded

**Comment by arekkas** [comment]
yup :+1:

**Comment by inyono** [comment]
also translation doesn't work
