### ISSUE TITLE
linked pictures don't work as links anymore

### ISSUE THREAD

**Issue by SimonKoehl** [serlo-org/athene2#129]
https://de.serlo.org/mathe

see "Zahlen und Größen", "Terme und Gleichungen" usw.

**Comment by inyono** [comment]
Linked pictures trigger magnific popup, see https://github.com/inyono/athene2/blob/mathjax-editor/src/assets/source/scripts/ATHENE2.js#L73

**Comment by arekkas** [comment]
This had already been fixed once: https://github.com/inyono/athene2/blob/mathjax-editor/src/assets/source/scripts/ATHENE2.js#L82-L84

I'm not sure why it isn't any more - maybe there were some BC breaking changes in magnific?

**Comment by inyono** [comment]
Ah, okay. That's because #124 isn't live yet, which fixed the bug introduced in commit 17598d7e59a524d5b0f07d4280ff4aceeea95145 (see https://github.com/serlo-org/athene2/commit/17598d7e59a524d5b0f07d4280ff4aceeea95145#diff-6dd7e1bc37b2b353319fa077541429c3R86)

**Comment by arekkas** [comment]
Ah right...nice catch :D
