### ISSUE TITLE
Courses don't show navigation

### ISSUE THREAD

**Issue by arekkas** [serlo-org/athene2#136]
https://de.serlo.org/mathe/zahlen-und-groessen/bruchrechnen-und-dezimalzahlen/umformen-von-bruechen-in-dezimalbrueche/ueberblick-zu-dezimalbrueche

works here: https://de.serlo.org/19495/was-ist-ein-dezimalbruch

can you fix this @Knorrke @creitiv please?

**Comment by Knorrke** [comment]
This should be fixed by merging origin/courses: That branch contains the logic for redirecting from the course to the first course page

**Comment by arekkas** [comment]
Oh right, my bad :)
