### ISSUE TITLE
Taxonomy tree changes in "organize" behave weird

### ISSUE THREAD

**Issue by aeneasr** [serlo-org/athene2#15]
By Renate:

> wir haben hier gerade das Problem, dass wir die Reihenfolge in der Taxonomy momentan offenbar nicht ändern können. Wir arbeiten am Lehrplanbaum, und wenn wir curriculum-topics verschieben und "Neue Reihenfolge speichern" drücken, geschieht anscheinend nichts. 
> 
> Nachdem ich später, als Philipp und Vanessa schon gegangen waren, noch alleine weitergearbeitet habe, scheint sich mir das Problem nun folgendermaßen darzustellen:
> - Wenn man "Sortieren" aufruft, die Elemente umsortiert und dann "Neue Reihenfolge speichern" drückt, muss man relativ lange warten, und dann erscheint die Meldung "Es gab einen unerwarteten Fehler. Bitte laden Sie die Seite neu." Der Sortiermodus bleibt dabei bestehen, d. h. die Felder mit den Strichen sind noch da.
> - Wenn man dann die Seite neu lädt, verschwindet der Sortiermodus und der Ordner, den man verschieben wollte, wird an der Stelle angezeigt, wo er vorher war, die Umsortierung hat also anscheinend nicht geklappt.
> - ABER: Wenn man etwas später noch einmal die Seite neu lädt, ist die Umordnung dann offenbar doch erfolgt! 

IIRC wird der taxonomy tree in der organizeAction gecached, es könnte also daran liegen, dass der Cache bei updates nicht invalidated wird und beim erneuten Laden somit der alte Baum angezeigt wird.

Alternativ müsste man investigieren, warum JS einen Fehler schmeißt, da dies ggf mit dem Cache zu tun haben könnte.

@inyono @daFischer

**Comment by inyono** [comment]
unfortunately, JS doesn't throw any error. The organize pages are weird anyway, since the left navigation shows both the backend and the subject navigation, see for example https://de.serlo.org/taxonomy/term/organize/18230

**Comment by arekkas** [comment]
@inyono what is the server's response?

I think #43 is related to this as well. I believe that invalidating the zfc-cache is the root cause for insanely high response times on these write operations. There is already a task on trello for moving the cache busting to a background worker instead of doing that in the request itself: https://trello.com/c/MQKLpeRl

**Comment by arekkas** [comment]
However, it would be good to check if these problems disappear when disabling cache busting

**Comment by inyono** [comment]
See above, server's status code is 500

**Comment by arekkas** [comment]
Not the status code, the actual response? Or is it empty?

**Comment by inyono** [comment]
Ah, sorry. But the response is not really helpful, either:
```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>500 Internal Server Error</title>
</head><body>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error or
misconfiguration and was unable to complete
your request.</p>
<p>Please contact the server administrator,
info-de@serlo.org and inform them of the time the error occurred,
and anything you might have done that may have
caused the error.</p>
<p>More information about this error may be available
in the server error log.</p>
</body></html>
```

**Comment by arekkas** [comment]
ok this is caused by an socket timeout (php taking to long to respond) so i am 70% sure this is solvable with https://trello.com/c/MQKLpeRl

**Comment by Knorrke** [comment]
I think this is closed via #699, reopen if there's something strange again.
