### ISSUE TITLE
loading Serlo video page fails

### ISSUE THREAD

**Issue by SimonKoehl** [serlo-org/athene2#154]
at Renate's Laptop, Firefox 39.0, Windows 7 Ultimate
It does work on my Laptop
![video_def](https://cloud.githubusercontent.com/assets/3379377/8774524/843e4cd8-2edf-11e5-89e2-c3386e3eebca.PNG)

**Comment by inyono** [comment]
Confirmed, Firefox 39.0, OS X 10.10.4. JS Console:
```
The character encoding of the HTML document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the page must be declared in the document or in the transfer protocol.
```

**Comment by arekkas** [comment]
This is most likely caused because varnish doesn't (currently) separate between AJAX and regular requests, but the backend does. If anyone has an idea (or link) how to fix this, it would be much appreciated.

**Comment by arekkas** [comment]
Remember: de.serlo.org/1234 is used for

a. redirecting
b. injections
