### ISSUE TITLE
topic folder in en.serlo has no breadcrums

### ISSUE THREAD

**Issue by SimonKoehl** [serlo-org/athene2#158]
https://en.serlo.org/math/numbers-and-quantities/decimal-fractions/comparing-decimal-fractions

parent taxonomy: https://en.serlo.org/math/numbers-and-quantities/decimal-fractions

**Comment by inyono** [comment]
Did you fix this yourself? It works now at least

**Comment by arekkas** [comment]
Always keep caching in mind, changes don't might not appear immediately

**Comment by inyono** [comment]
I know, but this only needs a simple change in the backend ;)
