### ISSUE TITLE
font size and color change

### ISSUE THREAD

**Issue by SimonKoehl** [serlo-org/athene2#166]
https://de.serlo.org/mathe/sonstiges-testen/testaufgaben

Some seconds after loading the page, font size and color change to bigger and more grey.

**Comment by arekkas** [comment]
caused by geogebra injection

**Comment by SimonKoehl** [comment]
.. which is a mess nearly on every computer I tested it.. Johannes should have finished his work properly..

**Comment by arekkas** [comment]
this geogebra injection is an old one

**Comment by arekkas** [comment]
i'll put it on trello

**Comment by SimonKoehl** [comment]
As far as I can see it, the only Applet on this page is a new one '>[Skizze](ggt/1393291)'

**Comment by arekkas** [comment]
looks like it was a problem with geogebra, works fine now

**Comment by arekkas** [comment]
nevermind..
