### ISSUE TITLE
Long lines of Latex code are not rendered properly in regards to the layout chosen

### ISSUE THREAD

**Issue by Solvagon** [serlo-org/athene2#169]
![bildschirmfoto vom 2015-07-30 14 30 30](https://cloud.githubusercontent.com/assets/11294607/8983099/92c99c68-36c7-11e5-8e1d-f4f05ef1f58f.png)

https://en.serlo.org/math/numbers-and-quantities/decimal-fractions/division-decimal-fractions/41856

**Comment by inyono** [comment]
That's one reason why I (personally) prefer the one-column layout. I guess we should at least break the columns on xs displays.
