### ISSUE TITLE
Jumping to discussions behaves weird in some cases

### ISSUE THREAD

**Issue by inyono** [serlo-org/athene2#182]
@creitiv by Renate: see https://de.serlo.org/mathe/stochastik/zufallsgroessen/gemischte-aufgaben-zu-zufallsgroessen-und-verteilungsfunktion/ , Exercise 6 ("Einem Paket mit Gläsern...). When you open the solution and press "Kommentieren", you can't scroll above a certain point (it keeps jumping back to the discussions). It works in some other cases, though (verified with current Safari)

**Comment by Knorrke** [comment]
Seems to be resolved (Probably since the new discussion design?). Please reopen, if problem appears again.
