### ISSUE TITLE
Feedback bei ladender Seite

### ISSUE THREAD

**Issue by inyono** [serlo-org/athene2#2]
Hatte jetzt paarmal den Fall (auf Live-Serlo), dass ich auf einen Link drücke, und die Seite erst ein paar Sekunden später lädt. Es ist aber nicht erkennbar, dass die Seite lädt (Ladekringel-Overlay o.ä.)?

**Comment by arekkas** [comment]
hm, könnte das an javascript/mathjax liegen, dass der browser inresponsive ist? wir können da auf jedenfall nicht viel machen
