### ISSUE TITLE
Link Terms of Use in registration form

### ISSUE THREAD

**Issue by Knorrke** [serlo-org/athene2#206]

**Comment by inyono** [comment]
@arekkas If we click on something other than the terms of service link, then the checkbox will be checked. Clicking on the link opens the terms of service. Is this a problem we should fix (e.g. by not linking the terms of service?) or should we rather just paste the url like in the editor?

<img width="789" alt="screen shot 2015-09-23 at 16 08 12" src="https://cloud.githubusercontent.com/assets/1508477/10047212/54f83fae-620d-11e5-8e6b-c6c6c9315b46.png">

**Comment by inyono** [comment]
or open ToS in new tab
