### ISSUE TITLE
Course , dropdown menu

### ISSUE THREAD

**Issue by TinsayeAbye** [serlo-org/athene2#209]
This menus are not easy to use. Especially when u have touchscreen. They disapeare when you put your finger away so you cant go to the section below.
 
<img width="577" alt="course" src="https://cloud.githubusercontent.com/assets/5862858/9943966/d7b03600-5d84-11e5-88d8-ca3fb8f703f0.PNG">

**Comment by inyono** [comment]
maybe related to #196
