### ISSUE TITLE
move templates to individual modules

### ISSUE THREAD

**Issue by philer** [serlo-org/athene2#21]
Non-pressing suggestion:
Currently all (?) templates are in `src/module/Ui/templates/`. Finding them the first time is a challenge, later it's inconvenient.

**Solution:** Each module has its templates in an individual subdirectory, like `src/module/<module>/templates/` or `src/module/<module>/views/`. This allows browsing all files relevant to a module in close proximity. It may also facilitate splitting of modules into stand-alone micro services later on.

**Alternative:** Following the monolythic structure we might also put everything in `src/templates/<module>`. Even better may be `src/views/twig/<module>`, to ensure that individual templates will be easy to replace if we ever decide to switch template engine (`src/views/<future>/`).
The advantage will be that templates are still easier to find (at least in my mind, twig files don't fit inside a PSR-style namespace directory structure) and closer to frontend assets.

**Outlook:** Applying that last thought (proximity of templates to assets like js & less) to the suggested solution above consequently leads to the idea of moving each individual modules assets in with the module as well. This might be a useful intermediate step to splitting athene2 into micro services.

My simple suggestion turned into rambling. Feedback appreciated.

**Comment by arekkas** [comment]
> **Alternative:** Following the monolythic structure we might also put everything in `src/templates/<module>`. Even better may be `src/views/twig/<module>`, to ensure that individual templates will be easy to replace if we ever decide to switch template engine (`src/views/<future>/`).
The advantage will be that templates are still easier to find (at least in my mind, twig files don't fit inside a PSR-style namespace directory structure) and closer to frontend assets.

I like this thought more than the first solution, because you almost always touch templates from more than one module. Having them in one place is convenient. Additionally, new devs might not find the templates right away if they are separated by modules.

**Comment by arekkas** [comment]
However, I wouldn't put twig and phtml templates in different directories.

**Comment by arekkas** [comment]
Closed due to stalling activity and low priority
