### ISSUE TITLE
Vagrant doesn't work anymore

### ISSUE THREAD

**Issue by inyono** [serlo-org/athene2#211]
Setting up a clean clone, vagrant doesn't work directly (currently investigating the cause).

Btw: Is there any reason we don't have a Ubuntu 14.04 LTS vm? 14.04 includes especially Node 10.* and PHP 5.5.* directly without relying on PPAs, so there would be some kind of stability...

**Comment by inyono** [comment]
Firstly, there are some PID conflicts on `service apache2 restart`:
```
There are processes named 'apache2' running which do not match your pid file which are left untouched in the name of safety, Please review the situation by hand.
```
Use `pidof apache2` to find out the PIDs and these processes with `kill -9 <ids>`. Another `service apache2 start` leads to
```
Output of config test was:
apache2: Syntax error on line 140 of /etc/apache2/apache2.conf: Syntax error on line 1 of /etc/apache2/mods-enabled/authz_default.load: Cannot load /usr/lib/apache2/modules/mod_authz_default.so into server: /usr/lib/apache2/modules/mod_authz_default.so: cannot open shared object file: No such file or directory
Action 'configtest' failed.
The Apache error log may have more information.
```

**Comment by inyono** [comment]
Working Vagrant:
* Apache/2.4.12 (Ubuntu)
* PHP 5.5.26-1+deb.sury.org~precise+1

Clean Vagrant:
* Apache/2.4.16 (Ubuntu)
* PHP 5.5.29-1+deb.sury.org~precise+3

**Comment by inyono** [comment]
Deactivating autz_default with `sudo a2dismod autz_default` leads to further errors:
```
Output of config test was:
AH00526: Syntax error on line 19 of /etc/apache2/mods-enabled/alias.conf:
Invalid command 'Require', perhaps misspelled or defined by a module not included in the server configuration
Action 'configtest' failed.
The Apache error log may have more information.
```

**Comment by arekkas** [comment]
Reason is that it is (or was) the official vagrant box. But we can of course upgrade the box if that fixes stuff.
