### ISSUE TITLE
Registration page throws fatal

### ISSUE THREAD

**Issue by arekkas** [serlo-org/athene2#237]
`An exception has been thrown during the rendering of a template ("No element by the name of [tos] found in form") in "user/user/register" at line 10.`

@inyono I believe this to be caused by your latest changes to the ToS thingy. Could you please take a look at it?

**Comment by inyono** [comment]
Are you sure that all files are updated? Since [user/user/register.twig](https://github.com/serlo-org/athene2/blob/master/src/module/Ui/templates/user/user/register.twig) has no more usage of `tos`

**Comment by arekkas** [comment]
Ok thanks, I'll look into it

**Comment by arekkas** [comment]
It was indeed a problem with the cache.
