### ISSUE TITLE
The en.Serlo.org/music page isn't working

### ISSUE THREAD

**Issue by JonasBley** [serlo-org/athene2#242]
The Music team is trying to create content on the Music page. However, the whole page seems to not work: https://en.serlo.org/music.

**Comment by abollithompson** [comment]
It surely isn't. To be exact my changes save in the backend, yet do not appear in the main page. (excuse my cave man tech language)

**Comment by arekkas** [comment]
What isn't working exactly? I currently see:

> Welcome to the music homepage of Serlo. The content provided here is meant to be used by students as well as contributors, educational institutions and teachers. All content can be copied, altered and distributed according to the Creative Commons license. 
This subject is currently in development.

**Comment by arekkas** [comment]
I made a minor change (in *active* development). That worked fine. Please be aware that you need to be **logged in** to see changes happen immediately. This is due to technical restrictions. The page facing anonymous users usually gets updated within 1-2 days.

**Comment by arekkas** [comment]
Please be also aware **that you need to check the checkbox on the bottom** which states:

>  By saving this page, you confirm that your contribution (including any edits you have made) is your own work, and that it does not infringe on the rights of third parties. You consent to publishing your contribution under the Creative Commons Attribution/Share-Alike License 4.0 (http://creativecommons.org/licenses/by-sa/4.0/) and/or under an equivalent license chosen by the Society for open education (Gesellschaft für freie Bildung e. V.) in accordance with the regulations laid out in the terms of use (http://de.serlo.org/21654). Should the contribution not be your own work, it must be available in accordance with the terms of use (http://de.serlo.org/21654), and you must agree to comply with any necessary license requests.

**Comment by JonasBley** [comment]
Yeah it seems to be working now, I guess it fixed itself. Thanks for the help! :)

**Comment by arekkas** [comment]
Ok I'll close this issue then. Feel free to reopen it if similar problems reoccur.

**Comment by abollithompson** [comment]
Danka
