### ISSUE TITLE
Pull philer/navigation

### ISSUE THREAD

**Issue by philer** [serlo-org/athene2#25]
Since I can't push/pull a new branch in this repo I'm letting you know here that the `navigation` branch in my fork contains my recent changes (I squashed them into one commit).

All I've really been able to do was the global layout with some basic responsiveness (css/html only). It's still a little rough around the edges. Here's the todo list:
* *anything in js*: I didn't even get to touch it.
* *mobile menu*: Right now all the regular menus get hidden in the mobile view but the mobile menu itself doesn't even exist yet.
* *work out what should happen with the right sidebar when it gets squashed*: Should the toggle stay behind or just hide it altogether?
* *clean up breakpoints*: `grep @media` will show you a random-ish usage of min-width vs. max-width
* *clean up comments*: I left a lot of stuff in for reference. You'll probably want to get rid of that eventually

If you've got any questions regarding my changes let me know.

**Comment by arekkas** [comment]
I created a new branch called `ui-navigation`, could you merge into that one?
