### ISSUE TITLE
wrong date a blog posts

### ISSUE THREAD

**Issue by SimonKoehl** [serlo-org/athene2#257]
Hinweis vom Kommunikation Team

Bei den Blogpost steht neben dem Titel der Autor und daneben eine Zeitangabe. Die Zeitangabe bezieht sich aber auf den release-timestamp und nicht auf das Veröffentlichungs-Datum, welches im Editor manuell angegeben wird. Es wäre super, wenn die aktuell Zeitangabe ("vor 3 Monaten" etct.) ersetzt wird durch "am DATUM)".

Danke!

**Comment by arekkas** [comment]
in trello übernommen
