### ISSUE TITLE
Neither backlink nor breadcrumps after you copy or batch move content

### ISSUE THREAD

**Issue by slevin777p** [serlo-org/athene2#271]
After you copied or batch moved content you get stuck at the page you moved them to, because there are no breadcrumps or backlinks.
![image](https://cloud.githubusercontent.com/assets/14125173/12090358/86c58b40-b2ee-11e5-9769-22989f17877a.png)

**Comment by arekkas** [comment]
i believe this issue is resolved? if so, feel free to close it :)
