### ISSUE TITLE
save butto in editor is dead

### ISSUE THREAD

**Issue by SimonKoehl** [serlo-org/athene2#272]
https://de.serlo.org/entity/repository/add-revision/1877
no reaction, by clicking on the SAVE button

**Comment by arekkas** [comment]
solved by https://github.com/serlo-org/athene2-editor/commit/77fea3e3f908b43acb46bf5291fb5eaea34deb16 might take a few secs until deploy

**Comment by arekkas** [comment]
it's live, make sure to delete caches or force hard reload
