### ISSUE TITLE
Scrolling triggers MathJax rendering on mobile devices

### ISSUE THREAD

**Issue by Knorrke** [serlo-org/athene2#273]
Scrolling in both Chrome and Firefox on Android 4.2.2 and Safari on iOS 9.2 causes MathJax to rerender.
Example page: de.serlo.org/2115

**Comment by Knorrke** [comment]
Apparently the resize event is triggered when scrolling on mobile devices, see:
https://stackoverflow.com/questions/9361968/javascript-resize-event-on-scroll-mobile 
https://stackoverflow.com/questions/17328742/mobile-chrome-fires-resize-event-on-scroll?lq=1

**Comment by arekkas** [comment]
i can confirm this. can you look for a fix @Knorrke :)
