### ISSUE TITLE
taxonomy content page headers should not be hX elements but have hX classes

### ISSUE THREAD

**Issue by arekkas** [serlo-org/athene2#278]

**Comment by elbotho** [comment]
why would that be better?

**Comment by Knorrke** [comment]
ping @arekkas 
I can't remember the reasoning, but had something to do with SEO...

**Comment by arekkas** [comment]
because it's a page full of headlines!

**Comment by Knorrke** [comment]
Ah ok, so its only the taxonomy pages and not in principle. So not relevant for #649
