### ISSUE TITLE
update text on /home

### ISSUE THREAD

**Issue by SimonKoehl** [serlo-org/athene2#286]
pls change descriptions text to:

"Serlo bietet einfache Erklärungen, 
tausende Aufgaben und Musterlösungen 
komplett kostenlos. Unsere Vision ist es, 
hochwertige Bildung weltweit frei 
verfügbar zu machen. Dafür bauen wir 
eine Wikipedia für’s Lernen."

.. or tell me how to do it my self.

thanks!

**Comment by inyono** [comment]
How about the english home page?

**Comment by SimonKoehl** [comment]
I asked Serlo Global for translation, but that might take a while, since Tobi and Jonas have exams. I'll open another issue, as soon as I got the translation
