### ISSUE TITLE
Link main headlines

### ISSUE THREAD

**Issue by inyono** [serlo-org/athene2#297]
i.e. serlo bird to homepage, subject title to its subject homepage. Don't link "Serlo", though...

**Comment by Knorrke** [comment]
@inyono I discussed this with @SimonKoehl, is there a reason why we don't link "Serlo" to the homepage too?

**Comment by inyono** [comment]
Yeah, there is a reason. If you also link Serlo, it could be confusing where the links lead to. Because "Serlo" and "Mathematik" can be seen together, but each part links to a different page.

**Comment by Knorrke** [comment]
Okay, that makes sense. I will change this tomorrow
