### ISSUE TITLE
Erstellungsdatum in Zukunft; kein Auftauchen bei neuen Bearbeitungen

### ISSUE THREAD

**Issue by inyono** [serlo-org/athene2#3]
Die Academy hatte jetzt mehrmals den Fall, dass ein Artikel erstellt wurde, und dann angezeigt wurde, dass der Artikel "vor x Minuten" erstellt wurde (Serverzeit / lokale PC-Zeit?) und dann auch (deshalb?) nicht bei den Bearbeitungen aufgetaucht ist.

**Comment by arekkas** [comment]
Die tauchen dann aber nach ein paar Minuten auf, oder?

**Comment by inyono** [comment]
Nein, sind nicht mehr aufgetaucht. Mussten das ein bisschen hacken über /entity/repository/history/id ...

**Comment by arekkas** [comment]
Falls du "neue Bearbeitungen" meinst, dort wird ein sehr starkes Caching verwendet welches mehrere Stunden läuft. Daher tauchen neue Bearbeitungen dort erst sehr zeitverzögert auf.

**Comment by inyono** [comment]
Ah, das könnte natürlich sein. Wobei manche der Bearbeitungen, die ja relativ zeitgleich waren, eben schon aufgetaucht sind

**Comment by arekkas** [comment]
Meinst du den Feed hier: https://de.serlo.org/mathe/entity/unrevised ?

**Comment by inyono** [comment]
Jap

**Comment by arekkas** [comment]
Ok, das caching wird hier festgelegt:

https://github.com/serlo-org/athene2/blob/master/src/module/Subject/src/Subject/Factory/SubjectStorageFactory.php#L33

Man könnte das ggf. auf 2-5 Minuten runterschrauben

**Comment by arekkas** [comment]
This has been solved
