### ISSUE TITLE
Icons for exercises

### ISSUE THREAD

**Issue by inyono** [serlo-org/athene2#317]
* [ ] Mark exercises from other subjects (i.e. bio exercise in math)
* [ ] Custom icons for individual exercises (currently "forschend", "Gruppenaufgabe", "haptisch")

**Comment by arekkas** [comment]
What icons should be used for this? Are there any visual prototypes? Otherwise I'm not sure if we can finish this in this sprint

**Comment by inyono** [comment]
has no design yet, AFAIK. So whoever tackles this issue, should talk with @elpoto

**Comment by arekkas** [comment]
ok, because icons for exercises are usually not included in font awesome and I think that they should be well chosen. we should also discuss what the goal is as icons are usually additive ("visualize an explanation") rather than a replacement for an explanation

**Comment by arekkas** [comment]
I will discuss this with @SimonKoehl

**Comment by SimonKoehl** [comment]
@arekkas this afternoon? I am flexible to talk about this for 10 minutes in between

**Comment by arekkas** [comment]
yes

**Comment by arekkas** [comment]
@SimonKoehl and I discussed that instead of having new meta data, this should actually be new types of content with interactions different from the ones that exist now on serlo. "Forschend" could include an upload field, "Gruppenaufgabe" a doodle, ...

**Comment by arekkas** [comment]
I don't see a clear path for resolving this currently, closing until the discussion comes up again.
