### ISSUE TITLE
Moving taxonomy trees doesn't work

### ISSUE THREAD

**Issue by JonasBley** [serlo-org/athene2#332]
Tried to move a taxonomy tree in the backend https://en.serlo.org/taxonomy/term/organize-all using the "sort" button, but resulted in an error message. Is there a different way to move taxonomy?

**Comment by arekkas** [comment]
hey, this can happen when you're doing too many changes at once. usually this happens when topics with the same name are moved into the same folder. try making your changes again but save after every 2-3 changes. if it doesn't work let me know

Sorry for the long response time.

**Comment by JonasBley** [comment]
So... if I want to move a whole topic tree, do I create a new one and move every folder one by one? That's a lot of work for just rearranging the order of some topics.

**Comment by arekkas** [comment]
That's not what i tried to say. Maybe you could give me more info like which topics you are trying to move where

Gesendet mit meinem HTC

----- Reply message -----
Von: "JonasBley" <notifications@github.com>
An: "serlo-org/athene2" <athene2@noreply.github.com>
Cc: "Aeneas" <aeneas@serlo.org>, "Assign" <assign@noreply.github.com>
Betreff: [serlo-org/athene2] Moving taxonomy trees doesn't work (#332)
Datum: Di., Apr. 26, 2016 22:27

So... if I want to move a whole topic tree, do I create a new one and move every folder one by one? That's a lot of work for just rearranging the order of some topics.

---

**Comment by arekkas** [comment]
@JonasBley sorry again, sometimes notifications get lost. If you're waiting for a response just write `ping @arekkas`. Usually you don't have to do that. It really depends which folder you wanted to move there. If you could give me that info I would be able to reconstruct your problem.

**Comment by SimonKoehl** [comment]
@arekkas I think I had the same proble here: https://de.serlo.org/biologie/ On Tuesday, I added "Zellbiologie" and tried to move it between "Biologie des Menschen" and "Genetik und Gentechnik"

**Comment by arekkas** [comment]
Exception:

```
/var/www/athene2/src/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:115

An exception occurred while executing 'INSERT INTO url_alias (alias, source, `timestamp`, uuid_id, instance_id) VALUES (?, ?, ?, ?, ?)' with params ["2016-10-03 10:05:11"]:

SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens
```

Stack:
```
#0 /var/www/athene2/src/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(128): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException))
#1 /var/www/athene2/src/vendor/doctrine/dbal/lib/Doctrine/DBAL/Statement.php(177): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'INSERT INTO url...', Array)
#2 /var/www/athene2/src/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(281): Doctrine\DBAL\Statement->execute()
#3 /var/www/athene2/src/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(1018): Doctrine\ORM\Persisters\Entity\BasicEntityPersister->executeInserts()
#4 /var/www/athene2/src/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(378): Doctrine\ORM\UnitOfWork->executeInserts(Object(Doctrine\ORM\Mapping\ClassMetadata))
#5 /var/www/athene2/src/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(356): Doctrine\ORM\UnitOfWork->commit(NULL)
#6 /var/www/athene2/src/module/Common/src/Common/Traits/FlushableTrait.php(17): Doctrine\ORM\EntityManager->flush()
#7 /var/www/athene2/src/module/Taxonomy/src/Taxonomy/Controller/TermController.php(174): Taxonomy\Manager\TaxonomyManager->flush()
#8 /var/www/athene2/src/data/classes.php.cache(85): Taxonomy\Controller\TermController->orderAction()
#9 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#10 /var/www/athene2/src/data/classes.php.cache(2): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#11 /var/www/athene2/src/data/classes.php.cache(2): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#12 /var/www/athene2/src/data/classes.php.cache(85): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#13 /var/www/athene2/src/data/classes.php.cache(2): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#14 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#15 /var/www/athene2/src/data/classes.php.cache(2): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#16 /var/www/athene2/src/data/classes.php.cache(2): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#17 /var/www/athene2/src/data/classes.php.cache(2): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#18 /var/www/athene2/src/public/index.php(25): Zend\Mvc\Application->run()
#19 {main}
```

**Comment by Knorrke** [comment]
This happens on every change in taxonomy now, and I don't know how to get the Exceptions, as they're not printed to the screen for some reason...

**Comment by Knorrke** [comment]
ping @arekkas

**Comment by Knorrke** [comment]
Ok so i think the problem I mentioned is a different one, that was probably introduced by the CSRF pull. (It works if I take out the csrf-token in https://github.com/serlo-org/athene2/blob/master/src/module/Taxonomy/src/Taxonomy/Form/TermForm.php#L25). I created a new issue #511
