### ISSUE TITLE
Search bar should stay fixed on top not laggy somwhere inbetween

### ISSUE THREAD

**Issue by arekkas** [serlo-org/athene2#340]
Sehr geehrte Damen und Herren,

ich bin Lehrer für Mathematik und Informatik und bin bei Recherchen für meinen Unterricht (Vektorrechnung) auf Ihre Seite gestoßen , die ich Inhaltlich für sehr ansprechend halte.

Leider musste ich feststellen dass Ihre dynamische Suchleiste ein angenehmes Ansehen ihrer Seite verhindert, da die Position der gesamten Seite permanent verschoben wird.

Rahmenbedingungen:
Tablet mit Android 5.0
Browser: Mozilla sowie Google Chrome.

Bei Mozilla lassen sich die Erweiterungen auch nicht aufklappen, bei Chrome hingegen schon.

Ich finde es sehr schade, dass so ein kleiner Effekt das Lesen Ihrer Seite so unangenehm gestaltet, zumal Ihre Inhalte sehr umfangreich und sicherlich lesenswert sind, dass man sie leider nicht in Ruhe zu Ende lesen kann, da dieser Effekt immens störend ist.

Machen Sie die Leiste statisch, der User kann ja Letzten Endes auch mal ein bisschen scrollen (schaden tut das bestimmt nicht :-) ). 

Ich wünsche noch einen schönen abend, oder den Lesezeitpunkt betreffend einen schönen Tag.

**Comment by inyono** [comment]
I can confirm that the search bar is not working correctly on Android. It works better on iOS, though (with a small delay, but okay IMHO)

**Comment by arekkas** [comment]
This happens because, instead of setting `style= "position: fixed; top: 0;"` when pinned to top, some javascript is setting `style="transform: translateY(123px)` which is constantly being updated and thus creates the laggy behaviour.
