### ISSUE TITLE
send welcome e-mail after e-mail confirmation

### ISSUE THREAD

**Issue by SimonKoehl** [serlo-org/athene2#341]
Text kommt noch

**Comment by SimonKoehl** [comment]
**Betreff:** Herzlich Willkommen bei Serlo
**Text:**
Liebe*r „Username“,

wir freuen uns, dass du an Serlo mitarbeiten möchtest!
Wo und wie du dich beteiligen kannst, erfährst du auf der Community-Startseite: https://de.serlo.org/community
Bei Fragen oder Problemen melde dich gerne bei community-de@serlo.org.

Viel Spaß mit Serlo!


**Subject:** Welcome to Serlo
**Text:**

Dear user,

We’re thrilled you’ve decided to contribute to Serlo. 
To find out how to get started on editing and creating content, please visit the community homepage: https://en.serlo.org/community.
If you have any questions, problems or feedback for us, feel free to get in touch via community-en@serlo.org.

Enjoy Serlo!

**Comment by arekkas** [comment]
Können wir diese E-Mail mit der Aktivierungsemail verknüpfen? Dann müssen wir nicht zwei emails schicken -> less likelyhood of spam filter

**Comment by arekkas** [comment]
blocking on @SimonKoehl reply

**Comment by SimonKoehl** [comment]
Würde ich nicht machen, da eine der beiden Sachen in der Mail leicht untergeht. Ist auch sonst sehr gewöhnlich, dass man zwei Mails bekommt.

Die Mail hätte dann zwei call to actions, die beide weg von der E-Mail hin zum Brwoser führen. Es ist unwahrscheinlich, dass sie wieder zu der Mail zurückkehren, wenn wir sie einmal zu Serlo.org geschickt haben
