### ISSUE TITLE
pictures of this page aren't loading

### ISSUE THREAD

**Issue by SimonKoehl** [serlo-org/athene2#347]
https://de.serlo.org/wirkung
there are two pictures in the content area, that aren't loading

**Comment by arekkas** [comment]
The last revision of that page works fine: https://de.serlo.org/page/revision/54401

There can be multiple causes for missing pictures, but most likely it's not a technical issue. Do you have the pictures somewhere on your drive? If so, please reupload them as there's not a lot I can do.

**Comment by arekkas** [comment]
If not, please reopen

**Comment by SimonKoehl** [comment]
it worked, thanks
