### ISSUE TITLE
course page sorting

### ISSUE THREAD

**Issue by arekkas** [serlo-org/athene2#348]
> Hey zusammen, ich wollte gerade in einem Kurs die Folien sortieren und habe dafür, während ich auf einer Kursseite war über das Aufklappmenü auf "Folien sortieren" geklickt. Dadurch bin ich dann auf eine mehr oder weniger leere Seite gelangt. Alex wusste dann zufällig, dass man die Folien wohl nur sortieren kann, wenn man genauso vorgeht, allerdings während man sich auf der "Inhalt"-Seite des Kurses befindet.
> 
> Ist das nur bei mir so oder ist das ein allgemeines Problem?
> 
> Wäre meiner Meinung nach ganz cool, wenn das mit dem sortieren immer klappt. Alternativ könnte man natürlich auch auf den "normalen" Kursseiten den Menüpunkt "Folien sortieren" rausnehmen. Die erste Lösung fände ich aber anwenderfreundlicher.

**Comment by arekkas** [comment]
@Knorrke did you forget to create a PR for this?

**Comment by Knorrke** [comment]
My commit removes the option from course-pages (or: from all elements with no childs), so it does fix the problem but it's not what this user asked for. Probably you could have an action for sorting the siblings to solve this in the requested way
