### ISSUE TITLE
Formula rendering is broken on iPad / Safari

### ISSUE THREAD

**Issue by SimonKoehl** [serlo-org/athene2#351]
Feedback from a Lab School student
It works with Chrome on iPad

**Comment by arekkas** [comment]
@SimonKoehl do we have the possibility to purchase second-hand tablets and smartphones? that way, we could anticipate those problems with testing. I also believe that we need some sort of continuous testing (test all devices every 2 weeks). Do we have capacities to introduce that?

**Comment by inyono** [comment]
Formula rendering works on my iPad just fine

**Comment by arekkas** [comment]
closing because not reproducible or information missing for reproduction and we have no way to test why it didn't work
