### ISSUE TITLE
Input challenges: allow multiple input challenges

### ISSUE THREAD

**Issue by inyono** [serlo-org/athene2#358]

**Comment by inyono** [comment]
Currently, we allow only one correct input challenge. So it is not possible to add multiple correct answers like `5x` and `5*x`. Should we allow this or should we rather add appropriate input types that cover such cases?

ping @arekkas @SimonKoehl

**Comment by arekkas** [comment]
You can not cover all possible possibilities manually, this should be done automatically.

**Comment by inyono** [comment]
In principle I agree. But then we need a couple of input challenges because of many different kinds of requirements. For example, consider exercises like `Factorize 5x + 20y`. Then we need the following solutions:
* `5(x+4y)`
* `5*(x+4y)`
* `(x+4y)5`
* `(x+4y)*5`
* all above but with `(4y+x)`

Now suppose that factorizing is not required in another exercise. So you need another type for that. Or exercises like `Apply associativity`. Again, this is different to the cases above. Fractions are another use case that probably require different kind of types.

Therefore, this approach leads to many different types (or types that are highly configurable). This makes it hard for editors to use those, even if we have some kind of "preview" beforehand.

**Comment by arekkas** [comment]
Now, can you imagine someone typing in all those different ways by hand?

Let's look at how khan academy has solved this?

**Comment by inyono** [comment]
Of course not, but it would allow prototyping in some cases.

Good idea with KA, although I suppose usability for editors isn't their top priority since they don't have a community that creates those exercises. I will look into this, though.

**Comment by arekkas** [comment]
Maybe we could use something like mathematica or wolfram to normalize the input?

**Comment by inyono** [comment]
I quickly look into http://khan.github.io/perseus/. It is basically a combination of configurable and multiple answers:
<img width="359" alt="screen shot 2016-06-19 at 12 29 54" src="https://cloud.githubusercontent.com/assets/1508477/16176836/5e8e0a6c-361a-11e6-8f68-21c5cb83cc04.png">
<img width="361" alt="screen shot 2016-06-19 at 12 30 58" src="https://cloud.githubusercontent.com/assets/1508477/16176837/5f887434-361a-11e6-9354-601fc631cd14.png">

See e.g. https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-equivalent-exp/cc-6th-distributive-property/e/distributive-property-with-variables

The problem with CASs is that we don't want the full power. So we would require a CAS that only applies some configurable simplifications. And I don't know a CAS that does this (this would be a pretty cool project, btw).

**Comment by arekkas** [comment]
I don't know one either, but I have never searched for one. Maybe KA uses some library that we could use?

I am against providing multiple inputs for equivalent solutions. I do not think that this feature will be used a lot by authors and even if, it will be very hard to anticipate all correct solutions. Additionally, chainging the exercise's task would imply changing 5-10 solutions as well. I'd rather keep it simple (only use it when the answer is clear) than introducing this to our content silo.

**Comment by inyono** [comment]
Okay, so we leave everything as it is and solve #307
