### ISSUE TITLE
Enable redirecting to parent in entity/view for some types

### ISSUE THREAD

**Issue by inyono** [serlo-org/athene2#363]
`entity/view` does not make sense for some entity types. For example, `input-challenge-*, `single-choice-*`, and even `solution` don't make sense without their context. IMHO, instead of having a page for those entities, we should instead redirect to their parent. This would make the workflow easier for editors, since one comes directly back to the corresponding exercise after editing. Furthermore, Google wouldn't index those useless pages.

Proposed solution: Add to `types.config.php` some parameter like `redirect-to-parent => true` (or `has-view => false`, ...). Then `indexAction()` in `Entity/Controller/PageController` reads the config of the entity and if this parameter is set, fetches its parents and redirects to the first.

@arekkas: What do you think? And is my proposed solution even possible?

**Comment by arekkas** [comment]
I'm not 100% sure but I think that this has been solved already. I might however be mistaken and I planned on implementing it. Either way, I think this is an important use case and should be covered

**Comment by arekkas** [comment]
Yes writing a new extension like `redirect` => 'My\Custom\Strategy' makes sense

**Comment by Knorrke** [comment]
We have a redirection implemented for the courses (the main course redirects to first course page). Probably this can be used or extended to match this usecase?

**Comment by inyono** [comment]
Nice, didn't know that! I guess we should tackle this in some of the next sprints :)
