### ISSUE TITLE
"Zuweisung zu Themen und Lehrplänen bearbeiten" geht nicht mehr richtig?

### ISSUE THREAD

**Issue by arekkas** [serlo-org/athene2#375]
> offenbar funktioniert der Punkt "Zuweisung zu Themen und Lehrplänen bearbeiten" (auf Lernobjekt-Ebene) nicht mehr richtig.
Ich habe ja in letzter Zeit kaum noch damit gearbeitet, sondern statt dessen wesentlich lieber "Elemente kopieren" bzw. "Elemente verschieben" (auf Ordner-Ebene) verwendet.

> Jetzt hatte ich mehrere Aufgaben mit "Elemente kopieren" einem Lehrplan-Aufgabenordner zugewiesen, und danach wollte ich drei der Aufgaben dann doch nicht in dem Lehrplan-Aufgabenordner haben.
Ich bin bei der jeweiligen Aufgabe auf den Menü-Punkt "Zuweisung zu Themen und Lehrplänen bearbeiten" gegangen, habe das entsprechende Häkchen entfernt und habe gespeichert.

> Aber die Aufgaben sind nach wie vor im Lehrplan-Aufgabenordner drinnen. Auch im Aktivitäts-Log findet sich kein Vermerk über meine Aktion.

**Comment by arekkas** [comment]
I'm sorry but vagrant gives me a blue screen since the latest service update. @inyono could you take a look?

**Comment by inyono** [comment]
Can't reproduce, works just fine locally.
