### ISSUE TITLE
Feedback Tool Prototyp

### ISSUE THREAD

**Issue by SimonKoehl** [serlo-org/athene2#376]
e.g. with
https://www.tellform.com/
https://www.typeform.com/

Specifications
- First step: simple positive/negative input with thumbs or stars
- Second step: Some questions with positive/negative input
- Third step: Text input
- Second and third steps should be optional (Previous steps should be saved without finishing all steps)
- the form input must be linked automatically to the learning content (article and course pages)
- show the tool to the right of the learning content maybe after scrolling

Questions are welcome to: simon@serlo.org

**Comment by arekkas** [comment]
this will be handled by a new member of serlo which is currently blocking on @SimonKoehl

**Comment by Knorrke** [comment]
resolved by hotjar
