### ISSUE TITLE
replace spoiler dropdown icon

### ISSUE THREAD

**Issue by SimonKoehl** [serlo-org/athene2#382]
I suggest to place the spoiler dropdown icon on the righ (see attachement)t. Some of our test users didn't get, that they can click on the spoiler.

Currant status
https://de.serlo.org/mathe/stochastik/relative-haeufigkeit-wahrscheinlichkeit/laplace-experiment

Suggestion:
![unbenannt](https://cloud.githubusercontent.com/assets/3379377/17554864/4a88574a-5f0d-11e6-944b-839424f912d8.png)

**Comment by Knorrke** [comment]
there is a bug somewhere, its not working properly.
