### ISSUE TITLE
Interactive Exercises: Trashed Items still apear

### ISSUE THREAD

**Issue by elbotho** [serlo-org/athene2#387]
Single and multiple choice answers still are displayed after being trashed. 

![bildschirmfoto 2016-08-30 um 12 57 57](https://cloud.githubusercontent.com/assets/1258870/18086721/8d8a91ee-6eb1-11e6-99a5-4d3200065e95.png)
(first item was trashed)

Logged in or not does not change issue.

Moving them to another exercise, or deleting the exercise works.

**Comment by inyono** [comment]
Also related: #370

**Comment by inyono** [comment]
Workaround: also remove the trashed entities from the trash bin
