### ISSUE TITLE
Hide "Show solution" in input-challenges if no solution created

### ISSUE THREAD

**Issue by Knorrke** [serlo-org/athene2#389]
In input-challenges currently the "Show solution" is displayed, even when there is no solution created.

**Comment by Knorrke** [comment]
This is most probably due to solution beeing defined but empty in https://github.com/serlo-org/athene2/blob/master/src/module/Ui/templates/entity/view/partials/input-challenge.twig#L21
So changing the statement to "if solution" should work.

I currently can't test it, so if someone wants to have a look at it, that would be great.

**Comment by arekkas** [comment]
I can't get vagrant running on windows right now...
