### ISSUE TITLE
Sprachversion wechseln

### ISSUE THREAD

**Issue by SimonKoehl** [serlo-org/athene2#398]
Wir brauchen bitte eine Möglichkeit zwischen den Sprachversionen von Serlo zu wechseln wie bei https://www.khanacademy.org/ im Footer oben rechts

Aktuelle Sprachversionen
- de.serlo.org, Deutsch
- en.serlo.org, English

**Comment by elbotho** [comment]
I think from a user perspective this might be misleading, because it might suggest that the same content is available in english (which it probably isn't).

Is the textlink to `Serlo.org in other languages` good enough for now?
Or should we build a selector?

**Comment by SimonKoehl** [comment]
I think, my prototype is good enough for the nearer future and I‘ll clarify the status of the language versions  on the selection page. Thank you!
