### ISSUE TITLE
Geogebra über HTTPS

### ISSUE THREAD

**Issue by inyono** [serlo-org/athene2#4]
Fehlermeldung im Serlo-Editor beim Öffnen vom Geogebra-Editor:

     Mixed Content: The page at 'https://de.serlo.org/entity/repository/add-revision/1877#' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://www.geogebra.org/geoip/geoip_json.php'. This request has been blocked; the content must be served over HTTPS.

**Comment by arekkas** [comment]
kannst du dich darum kümmern?

**Comment by inyono** [comment]
Jo, kann mich nur grad iwie nicht selber assignen :D

**Comment by arekkas** [comment]
ich auch nicht :O

**Comment by inyono** [comment]
Bei Geogebra 4.4 kann ich den Fehler nicht wirklich beheben, da `/geoip/geoip_json.php` iwo über diese js geladen wird, die auf `https://www.geogebra.org/web/5.0/web/web.nocache.js` liegt. Hab mal testweise Geogebra 5.0 ausprobiert, damit läuft zumindest mal wieder der Editor lokal ohne Fehler. Kann nur in Vagrant keine Bearbeitungen übernehmen:

```
Ein schwerwiegender Fehler ist aufgetreten
Während wir dieses Problem lösen, genieße das Video.


Zusätzliche Informationen:

Solarium\Exception\HttpException

Datei:
/var/www/src/vendor/solarium/solarium/library/Solarium/Core/Query/Result/Result.php:103
Nachricht:
Solr HTTP error: OK (400)
 
HTTP Status 400 - ERROR:unknown field 'content'
```
Ist das ein allgemeines Problem (heißt, kannst du bei deinem vagrant Überarbeitungen übernehmen)?

**Comment by arekkas** [comment]
Oh, das ist ja blöd, da ist solr nicht richtig eingerichtet. Ich habe bei vagrant noch nicht getestet ob Überarbeitungen funktionieren. Sieht aber sehr nach einem Fehler aus.
