### ISSUE TITLE
Update serlo bird and brand

### ISSUE THREAD

**Issue by Knorrke** [serlo-org/athene2#423]
- [x] update serlo bird: no line in feather
- [x] update brand font: letter-spacing and width of letters
- [x] reposition bird: Should line up with small letters of brand

old|new
----|----
![logo](https://cloud.githubusercontent.com/assets/11499926/18952083/accad6a0-8648-11e6-9674-0ca213906c15.png) | ![logo_new](https://cloud.githubusercontent.com/assets/11499926/18952153/f7bc50bc-8648-11e6-8cd8-82beb25378e8.png)

**Comment by elbotho** [comment]
I would suggest a svg version, but you probably now that already ;)

**Comment by Knorrke** [comment]
Thanks @elbotho, maybe you want to take a look at my PR #437? I updated the fonts there including the .svg font file.

**Comment by elbotho** [comment]
👍 
top. I meant to replace the whole font-face-thing with an svg image, but that's probably not a task for now.
