### ISSUE TITLE
unique link to user profile

### ISSUE THREAD

**Issue by SimonKoehl** [serlo-org/athene2#428]
user cant' link to their profiles because their URL is https://de.serlo.org/user/me

**Comment by Knorrke** [comment]
This seems to be a bit tricky. `/users/me` is included in the [navigation config](https://github.com/serlo-org/athene2/blob/master/src/config/instance/navigation/default.php#L236), so it's different from `/user/profile/<id>`, so just redirecting won't work. Also we can't include `/user/profile/<id>` in the navigation config, as we only want the page of the own id to have the options, not every user page. Any ideas @arekkas, @inyono?

**Comment by inyono** [comment]
Just to repeat my idea from Slack for documentation purposes: you could change the layout in the controller for `/user/profile/<id>` depending on the user id, so that the navigation is only shown when it is my own profile.

**Comment by arekkas** [comment]
Why not just add a link "Mein öffentliches profil" and link to the user id?
