### ISSUE TITLE
team.serlo.org doesn't work anymore (something with https)

### ISSUE THREAD

**Issue by SimonKoehl** [serlo-org/athene2#433]
team.serlo.org
![unbenannt](https://cloud.githubusercontent.com/assets/3379377/19195427/e55a07ba-8cb1-11e6-98eb-b130f7c2bc2b.PNG)

**Comment by arekkas** [comment]
not reproducible, neither in firefox, edge, safari no chrome

closing

**Comment by arekkas** [comment]
should be resolved now
