### ISSUE TITLE
comment area

### ISSUE THREAD

**Issue by SimonKoehl** [serlo-org/athene2#438]
Hi Benni,

I think we don't need this blue box:

![image](https://cloud.githubusercontent.com/assets/3379377/19443123/07096a86-948c-11e6-98b0-80bf1debddec.png)

And I think we should format the heading "Kommentare" as h2. As far as I know, a SEO rule is to have just 1 h1 per page. Youtube formats its comment area heading as h2 too: 

![image](https://cloud.githubusercontent.com/assets/3379377/19443263/7ec39754-948c-11e6-9ac3-6616e1359d8c.png)

**Comment by arekkas** [comment]
do not format with h2, only `<div class="h2">`. kommentare is not an essential part of sero content

**Comment by arekkas** [comment]
whoops, overlooked. it's already done the right way. @SimonKoehl this is not a h1, it just looks like one.

**Comment by SimonKoehl** [comment]
ah ok thanks, @arekkas 

just a detail: May be @Knorrke make it look like h2, because the comments are related to the h1 topic
