### ISSUE TITLE
litte problem with in-page navigation

### ISSUE THREAD

**Issue by SimonKoehl** [serlo-org/athene2#439]
http://serlo.org/mitmachen

please try one of the links on the content page e.g. https://de.serlo.org/mitmachen#alsorganisation 
the header you want to jump to is hidden behind the sticky breadcrums

**Comment by inyono** [comment]
@Knorrke Is this related to the changes introduced in #340?

**Comment by Knorrke** [comment]
@SimonKoehl was this working previously?

**Comment by arekkas** [comment]
yes, I remember that because I had to hack the offset
