### ISSUE TITLE
Multiple shades of grey in the background

### ISSUE THREAD

**Issue by inyono** [serlo-org/athene2#440]
![de serlo org-mitmachen](https://cloud.githubusercontent.com/assets/1508477/19489658/6748f3ae-956c-11e6-898a-598899e34cf6.png)

**Comment by Knorrke** [comment]
It's fine over here... 
![bildschirmfoto vom 2016-10-18 20 23 21](https://cloud.githubusercontent.com/assets/11499926/19491547/a5bf8894-9573-11e6-8a3a-e2cc56f51969.png)

Windows as well as Linux. Is it like this on every page on your laptop?

**Comment by inyono** [comment]
that's weird... Yes, every page in Chrome, not in Safari though

**Comment by arekkas** [comment]
can't reproduce on chrome windows

**Comment by inyono** [comment]
Weird... Well, it works here too after restarting...
