### ISSUE TITLE
open help in new tab

### ISSUE THREAD

**Issue by Knorrke** [serlo-org/athene2#449]
Links in the help menu of the editor should open in a new tab. You don't want to leave the editor to look up a markdown syntax.

![bildschirmfoto vom 2016-11-03 11 54 07](https://cloud.githubusercontent.com/assets/11499926/19963456/c83c51e0-a1bc-11e6-8a9d-e6ef4a6c6b6f.png)

**Comment by elbotho** [comment]
I think I have never seen this dropdown ❓  Where does it appear? 
Could the help page also open in an overlay like the video in the beginning?

**Comment by Knorrke** [comment]
It's in the editor, listelements might depend on the entity your editing.
Regarding Overlay: might be possible, but it's a serlo page like the guidelines, so you probably get some weird scroll in scroll and such things... don't know if that's the way to go.
