### ISSUE TITLE
notifications don't work

### ISSUE THREAD

**Issue by SimonKoehl** [serlo-org/athene2#451]
I created a comment on this article one hour ago: https://de.serlo.org/biologie/genetik-gentechnik/dna-genetik-molekuelebene/mutationen

The author didn't receive a notification, either online or via email.

**Comment by arekkas** [comment]
I received today a notifications. Because of increased load and spam 
problems notifications are generated every 6 hours at the moment.


Am 08.11.2016 um 14:37 schrieb Simon:

**Comment by SimonKoehl** [comment]
thank you!
