### ISSUE TITLE
API to show content in other platforms

### ISSUE THREAD

**Issue by joachimdieterich** [serlo-org/athene2#455]
Ich entwickle die Platform curriculum (digitaler Lehrplan) und würde gerne digitale Inhalte Ihrer Seite bei mir einbinden. Eine API dazu würde uns sehr helfen.

**Comment by SimonKoehl** [comment]
Lieber Herr Dietrich,
danke für die spannende Anfrage! Wir haben soeben kurz darüber geredet und besprechen das weiter in unserem nächsten Sprint Planning am 1.12.
Haben Sie einen Link zu der Plattform und können wir eventuell einen Testzugang erhalten?

**Comment by joachimdieterich** [comment]
Lieber Herr Koehl, 
hier der Link für den Gastzugang: [www.curriculumonline.de](www.curriculumonline.de)
Einen Zugang mit weiteren Rechten erhalten Sie per Email.

**Comment by SimonKoehl** [comment]
leider können wir ihnen gerade keine API zur Verfügung stellen
