### ISSUE TITLE
Hotjar-Umfragen mit JavaScript-Triggern aktivieren

### ISSUE THREAD

**Issue by eck-wal** [serlo-org/athene2#459]
Hotjar-Umfragen (siehe allgemein: https://docs.hotjar.com) können zielgenau auf bestimmten Seiten aktiviert werden, indem man JavaScript-Trigger in den HTML-Code integriert. (Dokumentation: https://docs.hotjar.com/docs/using-javascript-triggers ; Step 4 ist relevant).

Wir möchten jeweils eine Umfrage auf allen Seiten des Typs "Aufgabensammlung" und des Typs "Themenseite" anzeigen lassen. 

Die gewählten Trigger heißen: poll_themen_des1 ; poll_aufgaben_des1

Für die Umsetzung muss also auf jeder Seite des entsprechenden Typs folgende Zeile hinzugefügt werden:
Themenseite --> hj('trigger', 'poll_themen_des1'); 
Aufgabensammlung --> hj('trigger','poll_aufgaben_des1');

Kann das irgendwie automatisiert umgesetzt werden?

**Comment by Knorrke** [comment]
@eck-wal @arekkas Is this still relevant?

**Comment by Knorrke** [comment]
closing because stale.
