### ISSUE TITLE
German landing page feedback and improvements

### ISSUE THREAD

**Issue by arekkas** [serlo-org/athene2#463]
Collected feedback from slack:

* [ ] maik [5:52 PM] Auf mobile würde ich die Partner persönlich weiter unten anordnen.
* [ ] if the screen is small, you can scroll horizontally and the text is cut off
* [x] "hauptpartner" does not have margin/padding

**Comment by elbotho** [comment]
on small screens icons should always be colorful

**Comment by JonasBley** [comment]
Hm does Hauptpartner need padding? I would like to have a padding for the partner icons for the right screen size, but I don't know how to do that in css. 
I don't know why you can scroll horizontally, in my browser that's not possible. My pull requests seem to not be able to be merged, not sure what's going on there...
I made some other improvements, including elbotho's suggestion, can't create a proper pull request though.

**Comment by SimonKoehl** [comment]
in my opinion, the icons are too big and the subject name "Mathematik lernen" is too small. At the end, it is the key word "Mathematik" what addresses the users need.

**Comment by Knorrke** [comment]
There's something weird going on with the SVGs....
here two screenshots, one in firefox, one in chrome, looks completely different.... probably that's the same issue @SimonKoehl mentioned.
**Chrome:**
![Screenshot Chrome](https://cloud.githubusercontent.com/assets/11499926/20993843/33b61794-bced-11e6-8af8-cd72275ad672.png)
**Firefox**
![Screenshot Firefox](https://cloud.githubusercontent.com/assets/11499926/20993849/4235c472-bced-11e6-8e8d-c0600556ebb3.png)

@JonasBley any idea what's going on here?

**Comment by Knorrke** [comment]
console logs 
`Error: <svg> attribute width: Expected length, "auto"`

**Comment by arekkas** [comment]
I'm seeing this issue as well, @JonasBley please take a look

**Comment by arekkas** [comment]
Also, it looks like you are using flexbox within the bootstrap grid class, which in turn breaks in chrome (also, that's not the way you are supposed to use flexbox).

You can easily center elements with `margin: 0 auto`, if the have a smaller width than the parent element

**Comment by Knorrke** [comment]
@arekkas I discussed with @JonasBley, that I'll take a look at it, because he's quite busy atm.

**Comment by Knorrke** [comment]
@elbotho, @SimonKoehl, @arekkas Do you agree, that the size should be the one from Firefox? Or do you prefer the bigger version (Chrome)?

**Comment by arekkas** [comment]
firefox

**Comment by SimonKoehl** [comment]
jep, firefox

**Comment by elbotho** [comment]
puh, I'd go with in between, little bit bigger than firefox. 
If firefox-size: A bit less margin to the logo/slogan.

**Comment by Knorrke** [comment]
@elbotho like this?
![bildschirmfoto vom 2016-12-22 23 29 00](https://cloud.githubusercontent.com/assets/11499926/21442539/aceffde8-c89e-11e6-8c3f-426f54347e41.png)

**Comment by elbotho** [comment]
Suggestion: Less gray, icons little bit bigger, adapted margins. moves partners to next section.

![grafik](https://cloud.githubusercontent.com/assets/1258870/21651490/131d4b5c-d2a9-11e6-854f-dd8313fc6ff4.png)
ping @SimonKoehl 

if there is no strong resistance I'd put the css in a new branch (did it it css anyway). fine with you @arekkas ?
