### ISSUE TITLE
improve mobile

### ISSUE THREAD

**Issue by Knorrke** [serlo-org/athene2#465]
- on mobile there still is some gray space left and right from content, which should be removed
- related content doesn't need to be displayed on mobile (or maybe placed below the article/coursepage/...)
- the breadcrumbs are not visible and the backlink arrow is not enough to understand where you are right now.

Optimizations on mobile devices:
* [ ] remove gray area
* [ ] remove related content (or reposition it)
* [ ] show last breadcrumb below searchbar

**Comment by Knorrke** [comment]
Ping @SimonKoehl

I discussed this with @arekkas, and he said if you have the searchbar and the breadcrumb it might be too much stuff before the actual content (you have to scroll too far for seeing the content). His idea was to remove the search bar, because the search doesn't work properly anyway...

**Comment by SimonKoehl** [comment]
@Knorrke would be ok for me. But may be I have a better idea:

reduce search to just a button, that leads to https://de.serlo.org/search this way it could stay in line with the breadcrums?

**Comment by inyono** [comment]
hybrid idea: reduce search to just a button that toggles the search bar. So that mobile users don't have to load a new page when they want to search.

**Comment by SimonKoehl** [comment]
sounds good @inyono !
