### ISSUE TITLE
Check out einer neuen Revision wirft einen Fehler

### ISSUE THREAD

**Issue by SimonKoehl** [serlo-org/athene2#47]
![bildschirmfoto vom 2015-05-13 10 22 51](https://cloud.githubusercontent.com/assets/3379377/7606571/37a8b800-f95a-11e4-92d7-9e65226355e7.png)

**Comment by arekkas** [comment]
Reload the site. Problem is already covered in #43

**Comment by SimonKoehl** [comment]
ok, danke

(Beim dritten Mal ist ein schwerwiegender Fehler aufgetreten, beim vierten Mal hat's funktioniert)
