### ISSUE TITLE
New landing page - level 2

### ISSUE THREAD

**Issue by SimonKoehl** [serlo-org/athene2#471]
Mock up: https://docs.google.com/drawings/d/1rmTtmv0rKjhGNFaXEZD6itr6VnOvtT3wK9bcNKn_bKQ/edit

This iteration is about the next three sections from the mockup:
1) picture with explanations and USPs in the foreground
2) Wikipedia section
3) List of principles

dependencies
- "ok" from @elbotho for the overall design of the three sections
- two icons from @elbotho for section 1)

**Comment by elbotho** [comment]
@SimonKoehl for the icons, what do you think of the old choices? 

![grafik](https://cloud.githubusercontent.com/assets/1258870/21651253/35972f50-d2a8-11e6-8491-14e60d92e1f5.png)

I would love to move the partners from the first to the second section. see screenshot at #463 
Not quite sure where to move it though.

Sorry but I'm still not happy with 
> Gute Bildung braucht gute Prinzipien

What about smth like: 
> Unser Rezept für gute Bildung

**Comment by SimonKoehl** [comment]
My suggestion: No title. just the grafic

![img_0082](https://cloud.githubusercontent.com/assets/3379377/21653528/d77e856c-d2b1-11e6-82a4-8077768188c1.jpeg)

**Comment by elbotho** [comment]
ok, done!
![grafik](https://cloud.githubusercontent.com/assets/1258870/21891868/0066305a-d8d5-11e6-830c-79150d9da4e6.png)

can't upload zip files atm (no idea why) but will send svg on  request.

**Comment by JonasBley** [comment]
Sorry, much to do, couldn't get back on this until now. Also the next few days I will be busy. I have some questions regarding the landing page though, to make the task a bit clearer for myself:
1) The background in the mockup, should that be on the landing page too or do we keep the blue background?
2) The "selbstständig lernen" and "kostenlos und werbefrei" + logos will replace the current schülerlernen.svg, right?
3) Background color white, then grey after the blue (or whatever picture there will be) row is how it should look like? It seems to me it would be either a lot of empty, colorless space around "Serlo.org funktioniert wie die Wikipedia" or a text size that is much too large. 
4) The two additional partners will be added (see #480), it's just the logos so far have been grey, these are now green and blue. Is that right?

**Comment by SimonKoehl** [comment]
Hi Jonas!

1) Their should be the background picture, I'll send it to you via Mail
2) right! 
3) To answer your question, I updated the prototype. Of course, the messures aren't accurate and the Partners and the new grafic have to be transparent. 
4) see my comment on the other issue. The logos have to be grayscale.

Peace

**Comment by JonasBley** [comment]
Alright, that answers my questions, thanks!

**Comment by elbotho** [comment]
suggestion: replace gray with blue.
tried it in the mockup with the newsletter section. 
could imagine a version of the "prinzipien"-graphic on blue background like the "schüler lernen"-graphic atm.

@SimonKoehl what do u think?

**Comment by SimonKoehl** [comment]
I like your changes @elbotho 
Grafic on blue background: little too strong for my personal taste but let's try

@JonasBley I updated the textes again

**Comment by JonasBley** [comment]
Here are a few screenshots of where I am at: what do you think?
![screenshot 2017-03-02 17 33 58](https://cloud.githubusercontent.com/assets/14056541/23516818/95d57f32-ff6e-11e6-962a-36ff917c14cd.png)
![screenshot 2017-03-02 17 33 52](https://cloud.githubusercontent.com/assets/14056541/23516821/95da122c-ff6e-11e6-973e-c9cd647d4165.png)
![screenshot 2017-03-02 17 33 38](https://cloud.githubusercontent.com/assets/14056541/23516819/95d8d074-ff6e-11e6-9512-681c42dd7b63.png)
![screenshot 2017-03-02 17 34 14](https://cloud.githubusercontent.com/assets/14056541/23516823/95f64b9a-ff6e-11e6-96c5-93fed5aac3dd.png)
![screenshot 2017-03-02 17 34 08](https://cloud.githubusercontent.com/assets/14056541/23516820/95d90df0-ff6e-11e6-9853-bb23ef236a68.png)
![screenshot 2017-03-02 17 34 04](https://cloud.githubusercontent.com/assets/14056541/23516822/95dda4aa-ff6e-11e6-81f0-a6c237f13e4b.png)

**Comment by JonasBley** [comment]
ping @elbotho, @SimonKoehl

**Comment by SimonKoehl** [comment]
Yeah!

Ok, folgendes fällt mir auf:
- Icons bei "selbstädnig lernen" und bei "komplett kostenlos" sind zu groß
- zwei der Partner sind noch in Farbe. Entweder alle oder keine der Partner. Was denkst du @elbotho ?
- Alle Texte sollten eine größere Schriftgröße haben

**Comment by elbotho** [comment]
* the graphic should have a background color (and I'd prefere non-gray colors 😸  )
* logos in b/w 
* … more stuff

I'd like to play around with the styles a bit, @JonasBley did you commit it anywhere already?

**Comment by JonasBley** [comment]
I agree with your feedback, thanks! Here is the commit: 
https://github.com/JonasBley/athene2/tree/GermanLandingPageLevel2

**Comment by JonasBley** [comment]
What about a SerloBlue background for the graphic? Then we would have to turn around the colors on the outside, but I think it would look cool.
