### ISSUE TITLE
Registration should show flasher on landing page but doesn't

### ISSUE THREAD

**Issue by arekkas** [serlo-org/athene2#477]
I think this has to do with the new landing page. The old landing page showed a notification that showed "thank you for registering, we send you an registration email". The component that did that was called flasher

ping @Knorrke @elbotho @JonasBley

**Comment by Knorrke** [comment]
@arekkas Seems to me this is caused by caching. I can get messages on the starting page when logged in, however for registration process one isn't. Also, aparently the same problem already existet on the old landing page: #281 
Any idea how to fix this?

**Comment by arekkas** [comment]
This also happens during password reset. The cache is responsible for this.

**Comment by Knorrke** [comment]
superseded by #631
