### ISSUE TITLE
Declutter Menu(s)

### ISSUE THREAD

**Issue by elbotho** [serlo-org/athene2#482]
This is a screenshot of the "participate" part of the menu while not being logged in.
Could we exclude some items here?

- [ ] Things that are not accessible without login (_Ungeprüfte Bearbeitungen_, _Struktur_)
- [ ] Groups that are empty (_Arbeitsgruppen_)

![image](https://cloud.githubusercontent.com/assets/1258870/22852995/95c10f5e-f049-11e6-86cc-6a035606510c.png)

**Comment by inyono** [comment]
Set `needsIdentity` in navigation backend to `true`. Was this change already decided?

**Comment by elbotho** [comment]
I no of no discussion or decision. @SimonKoehl @arekkas what do you think?

**Comment by arekkas** [comment]
no opinion

**Comment by SimonKoehl** [comment]
Gerne löschen, was nicht genutzt wird. Können wir beim nächsten Planning machen

**Comment by SimonKoehl** [comment]
@elbotho Dass Navigationspunkte wie "Struktur bearbeiten" versteckt werden, das schreibe ich in die Richtlinien für den Bau der Navigation.

@elbotho Static pages, die ihr gelöscht haben wollt (alles außer neu hier, siehe Mathe?): Bitte mir eine Liste in eine Mail schreiben, dann kümmere ich mich darum.

**Comment by elbotho** [comment]
@SimonKoehl thanks, I sent you a mail.
@Knorrke can be closed soon :)
