### ISSUE TITLE
Replace icon from subtopics in taxonmy

### ISSUE THREAD

**Issue by Knorrke** [serlo-org/athene2#483]
Feedback from Tobias:
The icon for subtopics in taxonomy look like it's pointing towards the first entry. Maybe we could use a different icon that explains more what the links on the right are for.

Suggestion: replace font awesome chevron-right with font awesome folder-open-o (probably black as the other icons?)
![taxonomy](https://cloud.githubusercontent.com/assets/11499926/23209328/2425f69e-f8f9-11e6-815c-7aa08a345ad7.jpg)

@elbotho what do you think?

**Comment by elbotho** [comment]
Jup, I agree.

How inconvenient would it be to also add the number of entries in that folder behind the name e.g.

> Funktionsbegriff (3)
