### ISSUE TITLE
Enhancement: Add key words and key phrases to articles, courses and exercises that show up in searches

### ISSUE THREAD

**Issue by JonasBley** [serlo-org/athene2#491]
Issue is that pupils often can't find things they are looking for, because the search input doesn't fit the right article. An example is a boy in 5th grade, looking for "Anordnung von ganzen Zahlen" and seeing only an article relevant for university. 

The idea is that, in these specific cases, there is an extension to the editor where you can define key words that make it easier to find the article. There could be a field above "Änderungen". If someone searches for these keywords or phrases, they find the article they are attached to.

Maybe there is the possibility to find articles that are not read very often and adding key words to these articles so they are easier to find. Also, the Serlo Lab School is a perfect place to find out which articles are hard to find.

I don't know how hard it would be to implement. It would be cool if we found out by next week whether it is possible and how long it would take.

**Comment by inyono** [comment]
IMHO: it's super annoying if authors have to specify such meta data (in addition to being in compliance with our guidelines, etc.). We should rather invest more time into making the search better, see e.g. #479.

**Comment by JonasBley** [comment]
Agreed
