### ISSUE TITLE
remove head of horizon

### ISSUE THREAD

**Issue by SimonKoehl** [serlo-org/athene2#493]
... at least until we came up with something better

**Comment by SimonKoehl** [comment]
update: the use of the module changed but I think, we should still delete "Horizont erweitern __ Was ist das?"
What do you think @Knorrke ?

**Comment by Knorrke** [comment]
We could also change the description page linked at "Was ist das", but removing this is fine too.

**Comment by SimonKoehl** [comment]
I thought so, too. But let's just remove the texts. And may be leave the grey line?

**Comment by Knorrke** [comment]
Ok :+1:
