### ISSUE TITLE
serlo editor plugins

### ISSUE THREAD

**Issue by zepatrik** [serlo-org/athene2#497]
* [x] spoiler (collapsible layout item with title)
* [x] image as link
* [x] table (slate plugin?)

https://de.serlo.org/mathe/sonstiges-testen/test-sammlung

**Comment by inyono** [comment]
> * table (slate plugin?)

Just my two cents: I think we should implement this as a "smart" LayoutComponent. So that we don't have to reimplement DnD for tables and it just works out of the box.
