### ISSUE TITLE
Subjects on mobile not clickable

### ISSUE THREAD

**Issue by Knorrke** [serlo-org/athene2#499]

**Comment by Knorrke** [comment]
@JonasBley in the serlo-home file there are more closing div tags than opening ones thus closing the `.content` div too early at https://github.com/serlo-org/athene2/blob/94adf55a1026dcc3301f7d4b0040994e2a878d30/src/module/Ui/templates/layout/de/serlo-home.phtml#L198
I think you should just remove this, however this causes your padding in the `home-calls-wrapper` to look different, so maybe you want to change some styles too. Please take a look at this, as the landing page is really broken on mobile...

**Comment by JonasBley** [comment]
That should already be fixed and merged in #494 
I think it is not deployed yet though.

**Comment by inyono** [comment]
Unfortunately not. That PR is already deployed :/

**Comment by JonasBley** [comment]
Oh i see. That is weird as it worked for me when I tested it. I will look into it asap.

**Comment by Knorrke** [comment]
That PR was fixing the links in the home-calls-wrapper, but the subject icons still aren't clickable. Also the changes there are somewhat weird, as they normally shouldn't change anything on mobile^^ That's why I looked into it. I think removing the closing div tag mentioned above should solve those issues.

**Comment by JonasBley** [comment]
The change that I though would fix it was the col-sm-12 to col-xs-12 class change for the headlines. I thought the issue was that, for screen sizes smaller than md, the div around the title <h2>Serlo.org ist die Wikipedia fürs Lernen<h2> just wrapps around the whole page.

**Comment by JonasBley** [comment]
It makes sense that the closing div tag is the problem
