### ISSUE TITLE
Mission Statement in Footer einbinden

### ISSUE THREAD

**Issue by ronnitatserlo** [serlo-org/athene2#501]
Text: 
Serlo.org ist die Wikipedia fürs Lernen. Wir sind eine engagierte Gemeinschaft die daran arbeitet, hochwertige Bildung weltweit frei verfügbar zu machen. Unterstütze uns dabei mit einer Spende oder mach mit!

Anmerkungen:
"Spende" --> bold, verlinkt auf www.serlo.org/spenden
"mach mit" --> bold, verlinkt auf www.serlo.org/mitmachen

**Comment by ronnitatserlo** [comment]
@Knorrke

**Comment by elbotho** [comment]
@Knorrke Rough draft for new footer layout with mission statement
![_footer_draft](https://cloud.githubusercontent.com/assets/1258870/25448666/86278014-2ab9-11e7-92d8-1121cf1e7004.png)

**Comment by elbotho** [comment]
@Knorrke at least the colored boxed should NOT show on the landing page

**Comment by Knorrke** [comment]
@elbotho I think I'll start implementing this soon, do you have a sketch for the mobile version too? First Mission Statement and then the footer links probably, or do you want to change something there?

**Comment by elbotho** [comment]
Sorry, no mockup.
Yeah I like your suggestion. We can still think about not showing something if it is to much.

**Comment by Knorrke** [comment]
Ok, thanks, I'll keep you posted :)

**Comment by elbotho** [comment]
Here's the missing icon
[home_participate_icon.svg.zip](https://github.com/serlo-org/athene2/files/1148755/home_participate_icon.svg.zip)

**Comment by elbotho** [comment]
@Knorrke I set out to change some minor styles and ended up changing quite a bit.
You can look at the changes here:
https://github.com/elbotho/athene2/tree/footer-style-fixes

I'd like to move the Social Icons into their own menu category (see image below).
Could you have a look at [this](https://github.com/elbotho/athene2/commit/a2f3e8ae657225a9994f3be116b33735b85c29fb) 
and tell me how to add this to the navigation or do it yourself?
(`footer_social_navigation` would be the name)

#### how it looks now
![image](https://user-images.githubusercontent.com/1258870/30666347-486d2fbc-9e54-11e7-8f31-c0337125d8ff.png)

**Comment by Knorrke** [comment]
Thats actually already implemented - the previous footer had this already, you could look at the file befor my changes for details

**Comment by Knorrke** [comment]
here it is I think: https://github.com/serlo-org/athene2/pull/550/files#diff-b3fbac04fbb3595792583909cb9e9b2cL16
