### ISSUE TITLE
Implement banner campaign

### ISSUE THREAD

**Issue by elbotho** [serlo-org/athene2#515]
The general idea is to use images and text below the usual content to create brand awareness and show the people working behind the scenes.

I'd strongly prefere a coded implementation.

**Open Questions**
- [ ] How to store the content? (static or db)
- [ ] Show on every page / always or just once every few pages

**Position**
Between content and comments.

**Layout**
![bildschirmfoto 2017-05-09 um 16 20 12](https://cloud.githubusercontent.com/assets/1258870/26444708/b9f88178-413d-11e7-9fd1-3dbb9af8dd46.png)

**Implementation thoughts**
- div with green area and photo as background
- height determined by _min height_ and responding to text length

**Small screens version**
smth. like this
![image](https://cloud.githubusercontent.com/assets/1258870/26444804/255ebbf8-413e-11e7-89ad-8dab9e770341.png)

**Comment by Knorrke** [comment]
@elbotho I'd take a look at this in this months sprint, is there some progress to the open questions above? Do you want to meet to discuss this?

**Comment by elbotho** [comment]
Hey @Knorrke,
first one is a technical one, what do you need to decide if it makes sense to store it in the db?
I think the Idea is to change them one in a while.
Will discuss the second one with Ronnit.

**Comment by Knorrke** [comment]
I think the main question for the first one is, if you want to change the content frequently or if there are just some predefined banner. Predefined ones are easier to implement of course, but then changes have to go through software development.

**Comment by ronnitatserlo** [comment]
Is it possible to implement this in a way that I can modify the content without relying on dev to implement changes for me? It's not a must but if that is possible it would be nice to be able to change up the pictures and quotes (or add some) over time.

**Comment by Knorrke** [comment]
@ronnitatserlo I will probably reuse the horizon for this, then you can modify it without dev and the backend doesn't need much changing. So the biggest part is only implementing the design.

Is it correct, that the banner consists of only the picture, text and subtitle? Or do you need something else?

**Comment by elbotho** [comment]
currently picture, text and subtitle should be enough!

**Comment by ronnitatserlo** [comment]
Update: Links added to the texts (in case this is relevant here). https://docs.google.com/document/d/1kfpx7RTzjXCvSyZ73PbyXYskNjTLouu3Zj5_akB_ycg/edit#heading=h.25ijjvi6nlx9

**Comment by Knorrke** [comment]
@ronnitatserlo This actually poses some problems, as I was going to reuse the horizon for this and theres only a textfield without markup for the text... So including a link somewhere in the text is not supportet atm. Would it be okay to link the whole thing, like in the horizon?

**Comment by Knorrke** [comment]
@elbotho I'm almost done with this. Should the banner really be positioned between content and comments? 
And since I can't link single words in the text - should I link the whole whing (image + text + caption), or should I ignore the links?

**Comment by Knorrke** [comment]
Ok so in my pull request I solved this now by allowing link html-tags in caption and in the text. Also linebreaks are allowed in the text. Hope this solves the use case sufficiently @ronnitatserlo
