### ISSUE TITLE
add subject "Sex Education" to en.serlo.org

### ISSUE THREAD

**Issue by inyono** [serlo-org/athene2#532]
* id: sex-ed
* Deadline: 21.06.
* Contact: Tobias Müller
* Also move most stuff from https://en.serlo.org/math/other to that subject

@Knorrke Do you want to do this since you also self-assigned #525? Otherwise, I'd do both this weekend.

**Comment by Knorrke** [comment]
I'd really appreciate it if you could do that. I won't have much time this week...

**Comment by inyono** [comment]
Okay, will do

**Comment by Knorrke** [comment]
Thank you :)

**Comment by Knorrke** [comment]
@inyono any progress here? Can you hold the deadline or should I do it tomorrow?

**Comment by inyono** [comment]
@Knorrke will do this later today

**Comment by Knorrke** [comment]
Ok thanks! :)
