### ISSUE TITLE
Implement Pop-Up Form for Über Serlo Seiten

### ISSUE THREAD

**Issue by ronnitatserlo** [serlo-org/athene2#539]
This form is for the Über Serlo Seiten only. 

<script type="text/javascript" src="//s3.amazonaws.com/downloads.mailchimp.com/js/signup-forms/popup/embed.js" data-dojo-config="usePlainJson: true, isDebug: false"></script><script type="text/javascript">require(["mojo/signup-forms/Loader"], function(L) { L.start({"baseUrl":"mc.us7.list-manage.com","uuid":"23f4b04bf70ea485a766e532d","lid":"a7bb2bbc4f"}) })</script>

**Comment by Knorrke** [comment]
implement for the following sites:
https://de.serlo.org/serlo
https://de.serlo.org/paedagogik-konzept
https://de.serlo.org/qualitaet
https://de.serlo.org/schule
https://de.serlo.org/grundprinzipien
https://de.serlo.org/wirkung
https://de.serlo.org/software
https://de.serlo.org/transparenz
https://de.serlo.org/nutzungszahlen
https://de.serlo.org/plenum
https://de.serlo.org/jahresberichte
https://de.serlo.org/team
https://de.serlo.org/partner
https://de.serlo.org/serlo-geschichte
https://de.serlo.org/presse
https://de.serlo.org/mitmachen
https://de.serlo.org/jobs
https://de.serlo.org/kontakt
https://de.serlo.org/community
https://de.serlo.org/hilfe-startseite
https://de.serlo.org/community-werte
https://de.serlo.org/feature-suggestions
https://de.serlo.org/neue-faecher
https://de.serlo.org/richtlinien-horizont

**Comment by ronnitatserlo** [comment]
juhuu =)



Ronnit Wilmersdörffer | Finanzvorstand, Movement Building,
Projektkoordination Serlo ABC
ronnit@serlo.org <ronnit@serlo.org> | +49 179 958 5850
www.serlo.org <https://serlo.org/>
Serlo Education e.V.
Leopoldstr. 15
80802 München
Sitz des gemeinnützigen Vereins: München
Amtsgericht München VR 202808
Abonnieren Sie unseren Newsletter!
<http://serlo.us7.list-manage2.com/subscribe?u=23f4b04bf70ea485a766e532d&id=a7bb2bbc4f>

2017-08-28 15:18 GMT+02:00 Aeneas <notifications@github.com>:
