### ISSUE TITLE
Implement donation form to www.serlo.org/spenden

### ISSUE THREAD

**Issue by ronnitatserlo** [serlo-org/athene2#543]
Please set up URL www.serlo.org/spenden to display this form (and this form only):
```
<script type="text/javascript" src="https://secure.fundraisingbox.com/app/paymentJS?hash=gtfhzy5ijix2yy35"></script><noscript>Bitte Javascript aktivieren</noscript><a target="_blank" href="http://www.fundraisingbox.com"><img border="0" style="border: 0 !important" src="https://secure.fundraisingbox.com/images/FundraisingBox-Logo-Widget.png" alt="FundraisingBox Logo" /></a>
```

**Comment by elbotho** [comment]
Update: I got assigned with the design of this.
I suggest no changes until I'm done and we decide what kind of implementation makes sense.

**Comment by elbotho** [comment]
@Knorrke How much effort is it to create a custom page (custom content and css but basic layout, like the landing page but a lot simpler) on your end?

**Comment by Knorrke** [comment]
Not that much I think, ~1 day if its just a basic layout.

**Comment by elbotho** [comment]
Thanks @Knorrke,
Design is nearly done, let's talk when footer and the other stuff is done :) or if someone else has time.

**Comment by Knorrke** [comment]
Design by @elbotho is not impelemted in the previous PR, so I reopened this.
