### ISSUE TITLE
can't set navigation element position

### ISSUE THREAD

**Issue by SimonKoehl** [serlo-org/athene2#545]
I couldn't set a new position for a navigation element, that doesn't have a parent ID

Use case:
Change Position of "Über Serlo" from 30 to 10: https://de.serlo.org/navigation/container/get/3

**Comment by SimonKoehl** [comment]
Found a way arround the concrete use case by just rebuilding all elements of the top left navigation in a new order. But the bug is still in place

**Comment by Knorrke** [comment]
I'll look into it, but don't really know why this happens...
