### ISSUE TITLE
navigation parameter "needsidentity: true" doesn't work

### ISSUE THREAD

**Issue by SimonKoehl** [serlo-org/athene2#551]
This parameter and value are supposed to hide a navigation element from users who are not loged in. It's set e.g. for the trash bin in the maths navigation or for "AutorInnen-Community" in the top-right navigation.

**Comment by inyono** [comment]
Try `needsIdentity` (i.e. with a capitalised I) instead

**Comment by Knorrke** [comment]
Problem still exists, its used as `needsIdentity: true`, but has no effect.
