### ISSUE TITLE
inpage links: broken in spoilers

### ISSUE THREAD

**Issue by inyono** [serlo-org/athene2#575]
ping #572: Found another issue: if you have an header in the beginning a spoiler, you can't close the spoiler anymore (see e.g. exercises on math homepage)

**Comment by Knorrke** [comment]
can you provide a link, where this happens? If you meant the collapsible solution of the exercises, they work for me (tested both firefox and chrome)

**Comment by inyono** [comment]
e.g. `de.serlo.localhost:4567/mathe`. If you open a solution, you can't close it again. Tested in Safari. If you can't reproduce it, we will look into this on Monday, might be a problem with the new assets.

**Comment by Knorrke** [comment]
Can't reproduce that, works fine in my browsers. Does this happen on your Safari in de.serlo.org/mathe as well? Since the inpage-links change is already deployed you might want to check that...

**Comment by inyono** [comment]
Okay, seems like a problem with my new assets, I'll look into it
