### ISSUE TITLE
assets: improve local development and deployment strategies

### ISSUE THREAD

**Issue by aeneasr** [serlo-org/athene2#580]
Currently, unpkg is being used to fetch the latest updates from the new build system. While this is an ok solution for prototype testing, it makes development much harder as `npm publish` needs to be run prior to checking if the changes have indeed been done. I saw that the webpack-dev-server runs on it's on port. Maybe it's possible to use that local deployment in development (e.g. through env var) and save the hassle of changing the URL manually.

**Comment by inyono** [comment]
Yep, that's planned :)

**Comment by Knorrke** [comment]
Is this already fixed @inyono?

**Comment by inyono** [comment]
Well, kind of, as described in https://github.com/serlo-org/athene2#development. You have to change the url only in a single place. An environment variable or something similar would be a further improvement

**Comment by inyono** [comment]
Closed because of inactivity. Having to comment in a single line is good enough, imho
