### ISSUE TITLE
Replace/fix jquery.nestable

### ISSUE THREAD

**Issue by inyono** [serlo-org/athene2#585]
On touch devices, mouse click doesn't trigger events, see https://github.com/serlo-org/athene2/blob/4e5935ec4fed4284011e43176b4eaffb65216e20/src/assets/source/scripts/thirdparty/jquery.nestable.js#L29

**Comment by Knorrke** [comment]
judging by the code: This is fixed in a newer version, so we should update it and see if it works
Here is the repo: https://github.com/dbushell/Nestable
