### ISSUE TITLE
normalizer: issues with `’`

### ISSUE THREAD

**Issue by inyono** [serlo-org/athene2#586]
If title contains `’`, normalizer fails and maps url to `/`.

**Comment by inyono** [comment]
Nvm.... `https://en.serlo.org/85155` redirects to home page?

**Comment by Knorrke** [comment]
I can't reproduce this locally. I remember checking this on your laptop @inyono where it was reproducible. Can you check if that's still the case?

**Comment by inyono** [comment]
Can't reproduce this anymore.

**Comment by Knorrke** [comment]
I'll close this for now and reopen if it happens again.
