### ISSUE TITLE
Resetting Password breakes with HTTP 500

### ISSUE THREAD

**Issue by lehrer-pickhardt** [serlo-org/athene2#594]
When trying to reset a password with a valid registered email adress one receives HTTP 500. In the following the Request and Respons headers from Google Chrome in Inkognito mode (I removed my email adress for privacy reasons) cockies and so on should not be a problem. 

I was able to reproduce the problem also without inkognito mode. I don't know about other browsers but I would be sure 500 is always a serversided problem (:

Request URL:https://de.serlo.org/auth/password/restore
Request Method:POST
Status Code:500 
Remote Address:104.24.22.86:443
Referrer Policy:no-referrer-when-downgrade
Response Headers
age:0
alt-svc:clear
cache-control:no-store, no-cache, must-revalidate
cf-ray:3a826b7cdfd62732-FRA
content-security-policy:default-src https: 'unsafe-inline' 'unsafe-eval'; font-src: 'unsafe-inline' 'unsafe-eval' *; script-src https: www.google-analytics.com ajax.googleapis.com 'unsafe-inline' 'unsafe-eval'; img-src * data:
content-type:text/html; charset=UTF-8
date:Tue, 03 Oct 2017 19:48:36 GMT
expires:Thu, 19 Nov 1981 08:52:00 GMT
pragma:no-cache
server:cloudflare-nginx
status:500
strict-transport-security:max-age=15552000; includeSubDomains
via:1.1 google
via:1.1 varnish-v4, 1.1 google
x-cacheable:NO:TTL is 0
x-content-type-options:nosniff
x-frame-options:SAMEORIGIN
x-stroker-cache:Miss
x-varnish:7720808
x-varnish-cache:MISSED
x-xss-protection:1; mode=block
Request Headers
:authority:de.serlo.org
:method:POST
:path:/auth/password/restore
:scheme:https
accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
accept-encoding:gzip, deflate, br
accept-language:de,en-US;q=0.8,en;q=0.6
cache-control:max-age=0
content-length:83
content-type:application/x-www-form-urlencoded
cookie:__cfduid=db2dc4f4f3ce5973db9478cf8f86ba6f41507060089; PHPSESSID=9g372d45mjn5l9ajr53jk0d1s3; _gat=1; _hjIncludedInSample=1; _ga=GA1.2.93485145.1507060091; _gid=GA1.2.1900394137.1507060091; _gali=select-user
origin:https://de.serlo.org
referer:https://de.serlo.org/auth/password/restore
upgrade-insecure-requests:1
user-agent:Mozilla/5.0 (X11; CrOS armv7l 9592.85.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.112 Safari/537.36
Form Data
view source
view URL encoded
csrf:e9ff262b35ce41f74ca7b92f53240cfe
email: REMOVED FOR PRIVACY RESONS
submit:Restore

**Comment by arekkas** [comment]
The error is caused by our new 2FA policy which accidentally included the account sending out notifications, thank you for the report, I'll try to fix it asap.

**Comment by arekkas** [comment]
This has now been resolved. However, you will not receive a success flasher on serlo.org itself, but you will receive an email notification. This is currently caused by issue #477
