### ISSUE TITLE
static page disappeared

### ISSUE THREAD

**Issue by SimonKoehl** [serlo-org/athene2#610]
en.serlo.org/serlo 
(uuid: 23727)

other /serlo pages are still there: https://en.serlo.org/the-team

it still exists in the pages backend: https://en.serlo.org/pages

and in the navigation https://en.serlo.org/navigation/container/get/5

**Comment by arekkas** [comment]
What do you mean with disappeared?

**Comment by SimonKoehl** [comment]
This afternoon, it said "This page does not exist"

But now it is back .. 

:)
