### ISSUE TITLE
random success message

### ISSUE THREAD

**Issue by SimonKoehl** [serlo-org/athene2#612]
ist gerade aus dem Nichts bei mir aufgetaucht: 
![image](https://user-images.githubusercontent.com/3379377/32455917-15475118-c324-11e7-949f-928e3875eaab.png)

**Comment by arekkas** [comment]
This is caused by caching, a resolution could be to have a dedicated success page (e.g. /auth/register/success) that isn't cached.

**Comment by Knorrke** [comment]
superseded by #631
