### ISSUE TITLE
Translate labels of navigation elements in config files

### ISSUE THREAD

**Issue by inyono** [serlo-org/athene2#62]
For example, the labels of backend and profile pages are hardcoded in [config files](https://github.com/serlo-org/athene2/blob/master/src/config/instance/navigation/default.php) and therefore aren't translated.

**Comment by arekkas** [comment]
Some of them are being translated, see https://github.com/serlo-org/athene2/blob/master/src/module/Ui/templates/layout/navigation/horizontal.phtml#L49

**Comment by inyono** [comment]
Ah okay, I'll do that tomorrow
