### ISSUE TITLE
Check if most recent translations are used on live server

### ISSUE THREAD

**Issue by inyono** [serlo-org/athene2#626]
Problem: on https://de.serlo.org, some translated strings are still shown untranslated.

To reproduce:
* Open https://de.serlo.org/89143
* Select only answer "-2^6"
* Submit and see "Not quite. There is something missing!" which should be "Fast. Das sind noch nicht alle richtigen Antworten!" (as updated in https://github.com/serlo-org/athene2/commit/cdf70968164ec29a96a7f313ae2cbcbd278b33b0 a couple of weeks ago)

Might be a problem with the deployment script / live server config.

**Comment by Knorrke** [comment]
It's working now, I'll close this.
