### ISSUE TITLE
SEO: Start page – update headlines and SVG files

### ISSUE THREAD

**Issue by MMitzko** [serlo-org/athene2#649]
1) On the start page (serlo.org) “headlines” are not formatted as headlines in HTML, please set headlines H1-H3 to the start page and have a look that there are no empty headlines on the start page. Please refer: ![screenshot 22](https://user-images.githubusercontent.com/36268729/36251697-5b8e9ba0-1242-11e8-95ee-fc892eb98e1f.png)

H1 = Serlo Die freie Lernplattform
H2 = Mathematik lernen
H2 = Alphabetisierung für NeusprachlerInnen
H2 = Nachhaltigkeit lernen
H2 = Biologie lernen
H2 = Serlo.org ist die Wikipedia fürs Lernen
H3 = Zur Startseite für AutorInnen
H3 = Jobs und Engagement
H2 = Werden Sie Teil unserer Bewegung für freie Bildung
H3 = Mitglied werden
H3 = Spenden

2) The SVG files on the start page are suboptimal because they generate a lot of code. Goal would be to find solution that uses the SVG Files externally.

**Comment by Knorrke** [comment]
is this closed in #656 or is there something else to do?
