### ISSUE TITLE
SEO: Meta-Sites – set article enumerations as headlines 

### ISSUE THREAD

**Issue by MMitzko** [serlo-org/athene2#650]
Please set headlines on all Serlo Meta-Sites (for example: https://de.serlo.org/mathe/funktionen).

H1 = Title (z.B. Funktionen)
H2 = first main Topic (z.B. Funktionsbegriff)
H3 = first Topic (z.B. Funktionen und Relationen)
H3 = second Topic (z.B. Funktionen und Umkehrfunktionen)
H3 = third Topic (z.B. Verkettung und Fuktionen)
H2 = second main Topic (z.B. Wichtige Funktionstypen und ihre Eigenschaften)
And so on…

**Comment by Knorrke** [comment]
as discussed in our sprint planning: Instead of headings we should probably use `nav` elements.

**Comment by elbotho** [comment]
@MMitzko By Meta-Sites you refer to the Taxonomy-Pages (the content overview) right?

I will commit a solution in a sec. the whole page is a `<nav>` now , I use `<h2>` for the main topics (there are not to many in my opinion) and `<ul>` for the folders/links.

**Comment by MMitzko** [comment]
@elbotho yes, Meta-Sites refer to the Texonomy-Pages
