### ISSUE TITLE
SEO: Title Tag – create automatic generation

### ISSUE THREAD

**Issue by MMitzko** [serlo-org/athene2#654]
The Title Tag will be automatically generated within Serlo. Please create automatic Title Tag generation made of three parts:
1.	The given “Title” of the Article. (example: Parabel)
2.	The “TypeName” from the content in clinch. With these different types:

•	Artikel       	  -> keine Klammer
•	Video        	 -> (Video)
•	Kurs        	 -> (Kurs)
•	Kursseite   	  -> (Kurs)
•	topic        	 -> (Übersicht)
•	topic folder   	  -> keine Klammer (weil der Titel eh immer Aufgaben zu xyz heißen muss)
•	locale       	  -> (Lehrplan)
•	curriculum   	  -> (Lehrplan)
•	curriculum topic -> (Lehrplan)
•	curriculum folder -> (Lehrplan)

3.	The ending: “– lernen mit Serlo!“.

If a Title has more than 65 sings it gets shortened at the end. If possible: Make a fall-back-version. If the Title is longer than 65 sings remove first “lernen mit”. 
Improve the new Editor to show the number of written characters in the Title field. 
This Issue includes Issue #625 “Remove ">> Serlo.org" from page title appendix”

**Comment by Knorrke** [comment]
Addition from Sprint Planning: Show warning, if title field exceeds 65 characters

**Comment by MMitzko** [comment]
@Knorrke sorry for my late answer! It should not. It just should be removed if the Titel is to long.

**Comment by elbotho** [comment]
@arekkas 
There seems to be a `$postfix` automatically added to the string inside a zend helper. How is this set? Or is it easier to build the title string directly in the template?

**Comment by elbotho** [comment]
@MMitzko in the document it's 

> – lernen mit Serlo!
here the `!` is missing. What's the correct version?

**Comment by MMitzko** [comment]
@elbotho the correct version is with the !

**Comment by inyono** [comment]
Closed in #678
