### ISSUE TITLE
geogebra layout bug

### ISSUE THREAD

**Issue by SimonKoehl** [serlo-org/athene2#667]
test platform: Chromebook

https://de.serlo.org/mathe/geometrie/satzgruppe-pythagoras/satz-pythagoras
![screenshot](https://user-images.githubusercontent.com/3379377/39073958-f9cc70dc-44ef-11e8-881e-06d54f1e4cd9.png)

**Comment by inyono** [comment]
Occurs on specific device widths.

**Comment by Knorrke** [comment]
duplicate of #135
