### ISSUE TITLE
gap on the bottom of the footer

### ISSUE THREAD

**Issue by SimonKoehl** [serlo-org/athene2#668]
this appeared, because we added alements to the navigation

ping @elbotho 

![screenshot footer gap](https://user-images.githubusercontent.com/3379377/39074232-e3cf373c-44f0-11e8-8610-c6c6b5db5afc.png)

**Comment by elbotho** [comment]
Should be fixed with:
https://github.com/serlo-org/athene2-assets/pull/6

**Comment by SimonKoehl** [comment]
thanks!
