### ISSUE TITLE
Make new content visible for its authors

### ISSUE THREAD

**Issue by SimonKoehl** [serlo-org/athene2#680]
If some one with login rights creates e.g. a new article, it is very difficult to find this content again and to continue the editorial work. Also it could be disturbing, to "add content to this page (taxonomy)" but not actually see it there after clicking safe and returning to the taxonomy page.

My suggestion is, to display new content already on the taxonomy, although the first revision hasn't been approved yet. If you click on it, you will find the information "this has to be reviewed" - which leads the author the the revision, where he can continue to edit the content.

Open questions
- theoretical problem: This solution would allow users with login-rights to place an empty article with the titel "penis" in the taxonomy.
- Would this solution also work with exercises? 
- Are there further difficulties to solve this for courses?

What do you think?

**Comment by inyono** [comment]
Regarding "theoretical problem: This solution would allow users with login-rights to place an empty article with the title "penis" in the taxonomy.". We could only show unrevised content for users with login-rights.

**Comment by SimonKoehl** [comment]
good idea!
