### ISSUE TITLE
`authorization.identity.grant.role` broken

### ISSUE THREAD

**Issue by inyono** [serlo-org/athene2#681]
`german_langadmins` can't access roles like https://de.serlo.org/authorization/role/show/3 anymore to grant a user this specific role, although they have the right `authorization.identity.grant.role`.

**Comment by Knorrke** [comment]
Yeah that's a bug that was there all the time, you have to have the right `authorization.identity.grant.role` for all languages, and we created spanish and hindi tenants a little while ago.

**Comment by SimonKoehl** [comment]
@Knorrke we need this for two new authros, so I implemented:
- add this right to Spanish and Hindi langadmins
- added Nish as langadmin of the two new tenants

didn't work ..

**Comment by Knorrke** [comment]
I'll take a look in a minute.

**Comment by Knorrke** [comment]
ok, it looks like it's done as I meant, so maybe it's something else actually... Will have to look into it.

I added the `authorization.identity.revoke.role` right too, just to check, because that's the setup as it was before.

**Comment by Knorrke** [comment]
one thing, though: try to show the `german_....` roles, because I changed the login and guest roles to global rules (so we don't have to set them up for each tenant). That could cause, that those two roles can't be accessed without the right to grand global auths.

**Comment by SimonKoehl** [comment]
ok, I have no problems (may be because I am sysadmin) and added the new authors. 
Nish still can't access any roles.

**Comment by Knorrke** [comment]
Yeah, @SimonKoehl thats because you're sysadmin. I think I know whats the problem, @inyono. Since I changed the login rights to global and the other roles inherit these rules, you need the permission to grant roles for global... (which is associated to sysadmin). I think this is handled by the `Authorization/Assertions/RoleAssertion` file... Do you have a spontaneous idea how to fix this? Maybe also @arekkas

**Comment by Knorrke** [comment]
e.g. would it make sense to check only the permissions assotiated with the role and not it's parents?

**Comment by arekkas** [comment]
I strongly discourage changing the system. It works as intended and designed and messing with who can assign which roles is dangerous. Instead, it should be easier to start new tenants and "tenant"-specific roles should not have global access rights. Making it easier to start new tenants could be done with masks or helpers that use templates to create, for example, the required roles.

**Comment by Knorrke** [comment]
Would it make sense to remove the inheritance of the roles `german_reviewer` to `login`? That way the roles `german_*` would have only german rules, and the granting would work again.

**Comment by arekkas** [comment]
If we trust people to mess with the roles (i.e. grant or deny roles), why can we not trust them to also have rights to modify roles on different tenants? Why not create a new group "role_admin" that has the role right for any tenant?

Keep in mind that role_admins can (iirc) set superadmins

**Comment by Knorrke** [comment]
There's a role `authorization.identity.grant.role.sysadmin`, so I think that's a seperate thing.

Creating that role with global `authorization.identity.grant.role` and `authorization.identity.revoke.role` would work too, i guess. But it feels strange that `authorization.identity.grant.role` exists for the tenants but doesn't really work... But maybe I can do this for a quick fix and then implement an interface to change role inheritance. Then we could use the other option later.

**Comment by arekkas** [comment]
> But it feels strange that authorization.identity.grant.role exists for the tenants but doesn't really work...

It does work, but it only works when the tenants are isolated with regards to the role inheritance. :) I do understand the point though.

> But maybe I can do this for a quick fix and then implement an interface to change role inheritance. Then we could use the other option later.

Sounds good to me!

**Comment by Knorrke** [comment]
superseded by #701
