### ISSUE TITLE
SEO improvement - course meta description

### ISSUE THREAD

**Issue by SimonKoehl** [serlo-org/athene2#686]
course pages have no meta description. This is a problem especially for course pages without text (only video, applett, exercises, or picture)

On the other hand we don't want to have to write an meta description for every course page.

So our suggestion is to have a meta description on the level of the course, which is then loaded for every course page. That is not ideal because of double content but a lot better than now.

**Comment by SimonKoehl** [comment]
May be we can use the course "description". Courses still have this content field but it isn't used any more.

**Comment by Knorrke** [comment]
Why not add a meta-description field to course-pages with a fallback using the first paragraph as description?

**Comment by SimonKoehl** [comment]
many pages don't have text (only video, applett, exercises, or picture) and we don't want to have to write a meta description for all those course pages

**Comment by inyono** [comment]
The duplicated content issue (and some others) could be solved with #812.
