### ISSUE TITLE
Breadcrumbs don't work on dynamic routes

### ISSUE THREAD

**Issue by inyono** [serlo-org/athene2#69]
e.g. the user profiles, dynamic backend pages, etc.

**Comment by inyono** [comment]
@arekkas I worked out a solution different to what we discussed: If we add a fixed label to those dynamic pages, the breadcrumbs work the same as in other pages. For example, the breadcrumbs for `/navigation/container/get/2` are

> Backend < Navigation < Manage navigation

where only the last element is not linked. This makes it really easy to include other dynamic pages, because we only have to add the dynamic pages to `src/config/instance/xyz.php` with a appropriate label. Before I do this for the existing dynamic pages, do you see any problems in this approach? See #92

**Comment by arekkas** [comment]
Works, but all routes need to be updated then
