### ISSUE TITLE
exclude deleted elemets from sorting

### ISSUE THREAD

**Issue by SimonKoehl** [serlo-org/athene2#690]
eg. for this course: https://en.serlo.org/43357/welcome

there are several deleted course pages on the sorting page: https://en.serlo.org/entity/link/order/43238/link

imo they don't have to be there

**Comment by inyono** [comment]
General information:
* You get to the specified page by using the settings icon in any course and going to `Whole Course > Order children` where you can change the order of the children (i.e. course pages in this case)

To approach this:
* The template for the sorting page is defined in https://github.com/serlo-org/athene2/blob/master/src/module/Ui/templates/entity/link/order.twig (i.e. in `src/module/Ui/templates` and then mostly following the stuff in the url ;))
* Currently, we are iterating over all children, https://github.com/serlo-org/athene2/blob/master/src/module/Ui/templates/entity/link/order.twig#L20
* We can either filter the children in the templates directly, or (imho better) in its controller: https://github.com/serlo-org/athene2/blob/master/src/module/Entity/src/Entity/Controller/LinkController.php#L83.

**Comment by inyono** [comment]
Closed by #752
