### ISSUE TITLE
Fehler beim Taxonomy-backend

### ISSUE THREAD

**Issue by SimonKoehl** [serlo-org/athene2#7]
Ich würde gerne bei den letzten beiden Taxonomie-Elementen ein Unterelement hinzufügen allerdings steht mir das richtige Element "forum" nicht zur Auswahl: https://en.serlo.org/taxonomy/term/organize-all

Oder @arekkas habe ich da etwas falsch im Kopf? Aktuell bauen wir doch die Taxonomie so, dass mindestens eine "forum-categorie" am Anfang stehen muss und am Ende bei "Forum" die Diskussionen eingefügt werden können

**Comment by arekkas** [comment]
It's a bug

**Comment by arekkas** [comment]
Da es keine Foren mehr gibt aktuell nicht relevant
