### ISSUE TITLE
anchors of inpage links aren't cleared

### ISSUE THREAD

**Issue by Knorrke** [serlo-org/athene2#715]
If you follow a link with inpage anchor e.g. https://de.serlo.org/mitmachen#alsstudentin then that param `#alsstudentin` will stay there until you close the tab. Probably caused by the script of @inyono for `iframe` params, which appends the params to all links?

Also, same thing happens with `?redir=`, which probably shouldn't happen either.

**Comment by inyono** [comment]
Yep, will change it so that it only copies stuff needed for the content API. Nice catch.
