### ISSUE TITLE
vagrant ssh should bring me to /vagrant not /home/vagrant

### ISSUE THREAD

**Issue by arekkas** [serlo-org/athene2#72]
Solution: http://stackoverflow.com/questions/17864047/automatically-chdir-to-vagrant-directory-upon-vagrant-ssh

**Comment by inyono** [comment]
The given command `echo "\n\ncd /vagrant" >> /home/vagrant/.bashrc` didn't work directly, because `\n` was not changed into a newline. Just add `cd /vagrant` to the end of `.bashrc` :+1: Should we add this to some of the scripts?

**Comment by arekkas** [comment]
Yes, add it to the end of `./bin/vagrant/bootstrap.sh`
