### ISSUE TITLE
Merge athene2 and athene2-editor

### ISSUE THREAD

**Issue by arekkas** [serlo-org/athene2#74]
The workflow for doing editor changes is really bad. Should we merge athene2-editor into this repository?

cc @creitiv @inyono @jkempff

**Comment by inyono** [comment]
Maybe defining the editor as a [git submodule](https://git-scm.com/book/en/v2/Git-Tools-Submodules) will help? Don't we want to separate the development of the editor and athene2 in the future?

**Comment by arekkas** [comment]
That could probably work, do you want to look into it or, if you have any experience with git submodules, explain how they work @inyono ?

**Comment by inyono** [comment]
Seems like you can commit changes in git submodules: http://stackoverflow.com/questions/5542910/how-do-i-commit-changes-in-a-git-submodule I think that would make the workflow easier
