### ISSUE TITLE
history: missing changes

### ISSUE THREAD

**Issue by inyono** [serlo-org/athene2#779]
According to https://de.serlo.org/entity/repository/history/89525, the first revision (at time of writing) has changes "3 zu -3 und 1;5 zu 1,5". But if you go to the compare screen (https://de.serlo.org/entity/repository/compare/89525/121721), the changes aren't shown

**Comment by Knorrke** [comment]
- The template for the history is this one: [src/module/Ui/templates/entity/repository/history.twig](https://github.com/serlo-org/athene2/blob/b1170a383f0c582b04cd93e6df77e84912ec4d51/src/module/Ui/templates/entity/repository/history.twig). There the changes are displayed correctly.
- The template for the compare screen is [src/module/Ui/templates/entity/repository/compare-revision.twig](https://github.com/serlo-org/athene2/blob/development/src/module/Ui/templates/entity/repository/compare-revision.twig). There the changes aren't displayed.

Maybe also helpful: The data used in the template is passed by the controller [Entity/Controller/RepositoryController](https://github.com/serlo-org/athene2/blob/b1170a383f0c582b04cd93e6df77e84912ec4d51/src/module/Entity/src/Entity/Controller/RepositoryController.php)
