### ISSUE TITLE
fix errors stated in Eclipse PDT

### ISSUE THREAD

**Issue by marinusma** [serlo-org/athene2#794]
Currently developers working with Eclipse PDT are confronted with many "errors" mainly based on wrong use statements. Fix this please.

<img width="821" alt="bildschirmfoto 2018-11-13 um 15 13 13" src="https://user-images.githubusercontent.com/43985179/48418977-0e20c600-e757-11e8-930f-ba1b9b881665.png">

**Comment by aeneasr** [comment]
Are these errors even real? Eclipse is a really old system and PHP support - to my experience - is extremely limited. I recommend using PHPStorm instead.

**Comment by aeneasr** [comment]
Sorry, missed that it's the `use` annotations. In that case it could make sense to fix those!

**Comment by marinusma** [comment]
Background of the most errors were wrong types/classes in the phpdocs. Will have a look at PHPStrom and VSCode, thanks @aeneasr
