### ISSUE TITLE
Teilweise nicht klar, dass sich Hinweise/Lösungen geöffnet haben

### ISSUE THREAD

**Issue by inyono** [serlo-org/athene2#8]
Beispiel: https://de.serlo.org/mathe/geometrie/raeumliche-figuren/volumen-und-massenberechnung/gemischte-aufgaben-zu-volumen-und-massenberechnung/33945

Wenn man auf den Hinweis-/Lösungsknopf drückt, öffnet sich der entsprechende Teil unten auf der Seite unterhalb des sichtbaren Bereichs. Ich habe als Benutzer aber überhaupt keine Ahnung, dass sich überhaupt was an der Seite geändert.

**Comment by arekkas** [comment]
Moved to trello
