### ISSUE TITLE
Add persons to group serlo-org

### ISSUE THREAD

**Issue by kulla** [serlo-org/athene2#817]
@inyono Can you add the following persons to https://github.com/orgs/serlo-org/people:

* https://github.com/vroland
* https://github.com/Lodifice
* https://github.com/jakobwes
* https://github.com/SyntaxCacao

They shall be included in the new team https://github.com/orgs/serlo-org/teams/serlo-mfnf-devs We need this to include all MFNF repositories into https://github.com/serlo-org/ (see https://github.com/serlo-org/project-mfnf2serlo/issues/27 ).

(I am sorry to report this issue here. I wasn't sure, where I should do so :smile: ).

**Comment by kulla** [comment]
I can only invite members of the group serlo-org:

![screenshot from 2018-11-30 22-58-26](https://user-images.githubusercontent.com/1327215/49317156-9c38d280-f4f3-11e8-84c3-7df29ab2e362.png)

**Comment by inyono** [comment]
Sorry, didn't know that. They should all have an invitation to serlo-org and the MFNF dev team now.
