### ISSUE TITLE
Show original exercise in diff for an edit of a solution

### ISSUE THREAD

**Issue by kulla** [serlo-org/athene2#827]
When I check an unrevised edit for a solution it would be great to see also the original exercise text. Example (is an exercise part without the original exercise text):

![screenshot from 2018-12-06 20-22-27](https://user-images.githubusercontent.com/1327215/49607000-1efadb00-f995-11e8-8e96-35772ee1290f.png)

**Comment by inyono** [comment]
This will get solved with the new editor, so #wontfix
