### ISSUE TITLE
Delete old page https://de.serlo.org/muenchen

### ISSUE THREAD

**Issue by kulla** [serlo-org/athene2#833]

**Comment by Knorrke** [comment]
-> https://de.serlo.org/pages

**Comment by kulla** [comment]
I do not have access on this page :-) For the future: Such delete requests shall address Serlo admins?

**Comment by Knorrke** [comment]
@kulla I looked it up, you need to be `langadmin` of the specific tenant (in this case the `german_langadmin`) to delete the pages. So the request should adress one of them (currently Renate, inyono, wolfgang, Nish, Knorrke, Helly, peterjaumann, tobi_serlo, Rebi, metzgaria, kathongi, Flora_Jana, Niggo, tobias_lausser) or the community support.
