### ISSUE TITLE
breadcrumbs -> navi popover still working?

### ISSUE THREAD

**Issue by arekkas** [serlo-org/athene2#84]
![navibug](https://cloud.githubusercontent.com/assets/3372410/7778090/81905a7a-00c8-11e5-8369-6d7419a7f8b6.PNG)

https://de.serlo.org/mathe/zahlen-groessen/prozent-zinsrechnung/prozent

**Comment by inyono** [comment]
:-1: I'll look into it

**Comment by arekkas** [comment]
Still an issue on the live site. However, now all menu items are being displayed instead of only the breadcrumbs: https://de.serlo.org/mathe/zahlen-und-groessen


![serlobug132](https://cloud.githubusercontent.com/assets/3372410/7830916/cc6fa4e2-0451-11e5-89a9-dde414fd762e.PNG)
